### ISSUE TITLE
Problem with binding polymer-ui checked and value attributes

### ISSUE THREAD

**Issue by maxgrv** [aurelia/binding#103]
We are writing a fairly large mobile application using Aurelia, Cordova and Polymer UI components (1.0). Insofar the combination has worked very well.

The main problem we found out is that code like

       <paper-toggle-button checked.bind="isChecked"></paper-toggle-button>

does not work. 

Updates from the VM update correly the control but changes to the control DO NOT update the VM variable. Same thing happens also for text inputs.

Will Aurelia support these binding scenarios? Is it possible to make something like a custom binding adapter to cover these cases? We had the same problem some time ago also with Polymer 0.5 and KnockOut.js and we solved it writing a custom binding.

**Comment by EisenbergEffect** [comment]
This is possible today, you just need to tell Aurelia what the event is that is fired by the web component for the "to model" binding because the framework does not know what to bind to. You will also need to use the "two-way" binding command instead of "bind" because that will default to one-way binding.

To register the element configuration with the binding engine. You can do something like this in your bootstrapper code:

```
import {EventManager} from 'aurelia-framework';

export function configure(aurelia){
    var eventManager = aurelia.container.get(EventManager);
    eventManager.registerElementConfig({
      tagName:'paper-toggle-button',
      properties:{
        checked:['change']
      }
    });
}
```

Notice that the properties has the property name as key and then an array of events that the binding system should attach to in order to be called when the checked property changes. I don't know what that even is for your element, you would need to look that up in the docs. Once this is dine, it should work when you use a two-way binding.

It's possible that this may change in a future iteration. We are doing some work on the internals of our binding system soon. We would like some feedback on this. If you can think of a way to improve this of some sensible defaults, please share them. I'm wondering if we could, for example, use the "change" event by default for two-way bindings if there isn't a configuration specified.

Including @jdanyow here in case he has any ideas.

**Comment by maxgrv** [comment]
Thanks Rob. works like a charm using the 'change' event.

**Comment by shabalin** [comment]
Hi, I tried to apply same trick for https://elements.polymer-project.org/elements/iron-autogrow-textarea

```html
  <iron-autogrow-textarea bind-value.two-way="myValue"></iron-autogrow-textarea>
```

but the problem this component does not fire any event, docs says to use `bindValue` for two-way data binding, but unfortunately I could not make binding work in any direction. Could you please advice?

**Comment by EisenbergEffect** [comment]
@shabalin In your case, you need to set up an attribute map to map `bind-value` to `bindValue`. Then you can use `bind-value.bind` from our databinding system. You can do this in your bootstrapper code:

```
import {BindingLanguage} from 'aurelia-framework';

export function configure(aurelia){
  //normal bootstrap config goes here as per the docs

  let bindingLanguage = aurelia.container.get(BindingLanguage);
  bindingLanguage.attributeMap['bind-value'] = 'bindValue';
}
```

**Comment by EisenbergEffect** [comment]
I reopened this issue to investigate the original Polymer issues.

**Comment by shabalin** [comment]
Thank you for quick response!
- Copy-pasted the code you provided, got this
```
Unhandled promise rejection TypeError: Cannot set property 'bind-value' of undefined
    at y.configure (http://localhost:9000/dist/animation-main.js:21:48)
```
- commented out // bindingLanguage.attributeMap['bind-value'] = 'bindValue';
produces another error:
```
Unhandled promise rejection Error: A BindingLanguage must implement parseText(...)
    at BindingLanguage.parseText (http://localhost:9000/jspm_packages/github/aurelia/templating@0.13.5/index.js:293:13)
```

**Comment by EisenbergEffect** [comment]
Oops. Sorry. Hang on a sec. I'll get you the correct code...

**Comment by EisenbergEffect** [comment]
Ok. Sorry about that. Try using `import {TemplatingBindingLanguage} from 'aurelia-templating-binding';` instead. I accidentally gave you the abstract base class instead of the real implementation you needed to configure.

**Comment by shabalin** [comment]
Thanks a lot! After I installed 
```
jspm install aurelia-templating-binding
```
binding started working both ways! That's really cool!

**Comment by EisenbergEffect** [comment]
Excellent.
