### ISSUE TITLE
Global Functions not available to be called in template

### ISSUE THREAD

**Issue by AshleyGrant** [aurelia/binding#11]
The following will fail.

```html
<h2>${encodeURI(heading)}</h2>
```

Is this by design or a bug?

Stack trace is:
```
Potentially unhandled rejection [1] Error: encodeURI is not a function
    at ensureFunctionFromMap (http://localhost:9000/jspm_packages/github/aurelia/binding@0.3.2/system/ast.js:58:13)
    at CallScope.evaluate (http://localhost:9000/jspm_packages/github/aurelia/binding@0.3.2/system/ast.js:652:22)
    at CallScope.connect (http://localhost:9000/jspm_packages/github/aurelia/binding@0.3.2/system/ast.js:692:29)
    at InterpolationBinding.connect (http://localhost:9000/jspm_packages/github/aurelia/templating-binding@0.8.3/system/binding-language.js:232:35)
    at InterpolationBinding.bind (http://localhost:9000/jspm_packages/github/aurelia/templating-binding@0.8.3/system/binding-language.js:201:22)
    at View.bind (http://localhost:9000/jspm_packages/github/aurelia/templating@0.8.6/system/view.js:69:29)
    at RouterView.swap (http://localhost:9000/jspm_packages/github/aurelia/templating-router@0.9.2/system/router-view.js:85:49)
    at http://localhost:9000/jspm_packages/github/aurelia/router@0.5.1/system/navigation-context.js:72:37
    at Array.forEach (native)
    at http://localhost:9000/jspm_packages/github/aurelia/router@0.5.1/system/navigation-context.js:71:28es6-module-loader.src.js:139 (anonymous function)es6-module-loader.src.js:166 fes6-module-loader.src.js:188 i
```

**Comment by EisenbergEffect** [comment]
I'm not sure this is a good idea. I can imagine evil things.....What is the use case here?

**Comment by davismj** [comment]
<pre class="json-data">${$window.JSON.stringify(data)}</pre>

**Comment by jdanyow** [comment]
came up in the gitter today:  :point_up: [April 21 2015 7:27 AM](https://gitter.im/Aurelia/Discuss?at=553634060e3138bb6be8b3ee)

**Comment by chovy** [comment]
My simple use case is a global alert on the page. I want to be able to trigger it from anywhere in the app.

// app.html (layout file)
`<div class="alert" if.bind="message">${message}</div>`

// components/thing/edit.js (after update succeeds)
a
nd from a controller or wherever I would call `rootScope.message = 'Success! Yay!';` to trigger it.

perhaps there is a better way for my use case?

**Comment by davismj** [comment]
```<pre>JSON.stringify(object)</pre>``` +1

**Comment by jdanyow** [comment]
@chovy for your specific case I think you'd be better off creating a class:

```javascript
export class GlobalAlert {
  message = null;
  setMessage(message, timeout = 5000) {
    this.message = message;
    if (timeout) {
      setTimeout(()=>this.message = null, timeout);
    }
  }
}
```

Then you can `@inject` the class into the main view model that the alert markup will be bound to as well as any other class that needs to create alerts.  This will make it easier to refactor the alerting system in the future.  It also makes it very clear which view-models have a dependency on the alerting system.

@davismj agree :+1:

**Comment by jods4** [comment]
I wanted this at first as well. Especially when thinking about it like I did with Knockout on "older-school" projects that were smaller and not big SPAs and didn't use modules.

Approaching Aurelia with a SPA state of mind, I am not sure if there are good use cases anymore.

- Modules bring sanity to JS projects. But then once you start using modules there's very little to use in the global scope. In fact, almost nothing! And adding stuff on `window` for the sole purpose of being able to access it directly in a binding is very wrong.

- Examples like `encodeUri` or `JSON.stringify` should be handled by value converters I think. That's exactly what they are for: `<pre>${ object | json }</pre>`. If you weren't lucky that those two are globals it's what you would have had to do anyway (e.g. if you want `XML.stringify`). Alternatively, one-shot formatting could be put inside a computed property in the ViewModel with the proper `@computed` dependency.

- @chovy's example is polluting the global namespace. I think a better solution is for your layout / `app.js` to export the alerting function as @jdanyow suggested or to use an event bus (`aurelia-event-aggregator`) in the app.

- I find myself using consts or enums and wishing they were accessible in my bindings. E.g. `<div if.bind='state === StatesEnum.Active'>`. But then, because of modules the only way to do that would be putting them in the global namespace, which feels wrong. I think the proper way is to say: the view requires those value, so the ViewModel needs to expose them. I.e. I import them on the VM. Alternatively I could expose a computed property `isActive`, as suggested for the converters.

So in the end, I am not sure what the postchild usecase for this is, baring technical feasability.

**Comment by davismj** [comment]
Agreed.

**Comment by EisenbergEffect** [comment]
I agree as well. Closing this.
