### ISSUE TITLE
Binding <select> to integers

### ISSUE THREAD

**Issue by JeroenVinke** [aurelia/binding#141]
Is there an easy way to bind `<select>` dropdowns to integers in the viewmodel, without it changing the type of the property to string?

I made a plunker: http://plnkr.co/Nq1oHC

**Comment by jdanyow** [comment]
The html option element's value property is of type string.  Anything you assign/bind to it will be cast to a string.  Aurelia looks for a special `model` property on the options and will use it instead of the `value` property if it's available.  The `model` property can be of any type.

Here's how you would use number literals:

```html
<select value.bind="genderNumber">
  <option model.bind="1">Male</option>
  <option model.bind="2">Female</option>
</select>
```
*notice we're using `model.bind`... this ensures the aurelia parser is used and `"1"` is parsed as a number literal.  If we used `model="1"`, the model property would be of type string.*


Here's how you would bind to number data:

```javascript
export class Foo  {
  genders = [{ code: null, name: '(unanswered)' }, { code: 1, name: 'Male' }, { code: 2, name: 'Female'}];
  genderNumber = null;
}
```

```html
<select value.bind="genderNumber">
  <option repeat.for="gender of genders" model.bind="gender.code">${gender.name}</option>
</select>
```

**Comment by JeroenVinke** [comment]
Makes sense! Thanks!

**Comment by NeelapareddyReshma** [comment]
we have added the drop down code like the below, but we are not getting how to map the URL
here and are the custom tags.
in html
 here voya-field and voya-option are the custom tags
----------------------------------------
<div class="max-width-container"> <voya-field type="select" label="Select an account" hide-label class="select-type" style="width:100px;"> <voya-option repeat.for="option of options.countries" model.bind="option" value.bind="selectedOption"> ${option.IDTEXT}</voya-option> </voya-field> </div>
----------------------------------
js-file

@observable()
selectedOption;

options = {
countries: [
  { ID: '001', IDTEXT: 'Country 1' },
  { ID: '002', IDTEXT: 'Country 2' }
]
};
selectedOptionChanged(option) {
if (option && option.ID === '001') {
location = '#/retirement/details/5120B4FE280E6F3C677E9F039F2B8EDEE299115519A4CCDAFEE3BFA9C483996F/showsub';
}
}

here how to map the lint to first drop down.

**Comment by NeelapareddyReshma** [comment]
here how to map the list to first drop down.
