### ISSUE TITLE
Reference to a custom element's class instance within another custom element

### ISSUE THREAD

**Issue by hlege** [aurelia/binding#144]
I would like to have a reference in my `TopLevelViewModel` to the `barElement`. My `<foo-element>` creates a variable called `$parent`, so I can reference variables from my `TopLevelViewModel`. However the following code only creates a variable called `this["$parent.barElement"]` in the `<foo-element>`'s viewModel, instead of resolving the dot-notation.

```xml
<template>
    <require from='foo-element'></require>
    <require from='bar-element'></require>
    <section class="au-animate">
        <h2>${heading}</h2>
        <foo-element>
            <bar-element  bar-element.ref="$parent.barElement"/>
        </foo-element>
    </section>
</template>
```
```js
export class TopLevelViewModel{
	constructor(){
		this.heading = "Foo";
	}

	someMethod(){
		this.barElement.doSomething();
	}
}
```

Currently i can only do this.
```xml
<template>
    <require from='foo-element'></require>
    <require from='bar-element'></require>
    <section class="au-animate">
        <h2>${heading}</h2>
        <foo-element foo-element.ref="fooElement">
            <bar-element bar-element.ref="barElement"/>
        </foo-element>
    </section>
</template>
```
In the top level view model:
```js
  export class TopLevelViewModel{
	constructor(){
		this.heading = "Foo";
	}

	someMethod(){
		this.fooElement.barElement.doSomething();
	}
}
```

**Comment by EisenbergEffect** [comment]
`ref` doesn't take a binding expression, but only a property name to use as the reference. In order to get a reference to a child, you should use the `@sync('selector') child;` decorator/property in your parent. This will create an array property named "child" that is synchronized with child elements that match the css selector. We will be improving this in the next release, so it will be renamed `@queryAll`. We'll also be adding `@query` for single element hookup instead of arrays of all matching elements.

**Comment by gautamsi** [comment]
I tried using `@child` and `@children` it does not provide instance of child custom element, any pointers please.
