### ISSUE TITLE
Ability to ignore changes with value equality

### ISSUE THREAD

**Issue by ejsmith** [aurelia/binding#146]
In my code, I am setting an observed property to a new instance of an object, but all of the object properties are identical to the previous properties. I would prefer to not trigger a change notification when the values are the same.

**Comment by pwelter34** [comment]
Here is an example scenario where it would be useful to override equality determination.  In my application, there is a shared organization instance that is injected into view models.  On various application changes, the refresh method is called.  Because of the complexity of the application, it can sometimes be called multiple times even if there really wasn't a change.  The issue is when the property is set several times, there is a UI refresh because change tracking detected change.  

This is how I'm solving the problem now.  Would be nice if there was a framework way to override equality determination.

    public currentOrganization: Organization = null;
    
    public refreshOrganization() {
        if (!this.currentUser)
            return;

        // update current organization
        this.organizationRepository.getById(this.currentUser.current_organization_id).then(organization => {
            console.log("currentOrganization updated");

            // prevent double refresh, compare json to see if it should be updated
            let j1 = JSON.stringify(this.currentOrganization);
            let j2 = JSON.stringify(organization);

            if (j1 != j2)
                this.currentOrganization = organization;

        });
    }

**Comment by stoffeastrom** [comment]
Out of curiosity, why do you guys have new instances? I mean in your example @pwelter34 if you used JSONPatch when loading from the server you still would have the same reference.

**Comment by jdanyow** [comment]
You could also use `Object.assign`.

change:

```js
this.myProperty = differentObjectWithSamePropertyValues;
```

To:

```js
Object.assign(this.myProperty, differentObjectWithSamePropertyValues);
```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign
