### ISSUE TITLE
text inputs bound to non-existent values show up as "undefined" in composed elements

### ISSUE THREAD

**Issue by mbroadst** [aurelia/binding#152]
relevant plunker: http://plnkr.co/edit/Yzs2RXNJynmkjX3k1RcA

**whats going on here**
This plunker contains an element (MyDialog) which composes another element (MyDialogContent), and binds a single value from the top level all the way to the composed element (object is bound to my-dialog, and my-dialog binds the same object to my-dialog-content's model in `activate`).

**expectations**
  * click "ADD" - all input boxes show up empty
  * click "UPDATE" - input boxes contain the values of relevant properties on bound object

**actual result**
  * click "ADD" - all input boxes show "undefined" (_incorrect_)
  * click "UPDATE" - input boxes contain the values of relevant properties on bound object (_correct_)

Interestingly enough, if you modify the definition of MyDialogContent to contain a `record = {}` at the top, the initial rendered view is correct (each field displays an empty string, or in this case the placeholder text). Once you click "ADD", the broken behavior exhibits itself again.

**Comment by mbroadst** [comment]
This appears to be unrelated to composition as I initially thought, this plunker exhibits the issue with a simple VM: http://plnkr.co/edit/xJoTFhkYCyYtaaGWhSLo

**Comment by mbroadst** [comment]
For further reference (and weirdness), here is a link to a fork of a plunker @jdanyow gave me earlier. I've added three inputs to always bind to the current `editing` member, when you click "Add new planet" the value for `editing.name` shows as undefined, however the other two fields correctly display as empty strings: http://plnkr.co/edit/ulpjUa6EbFpZzgOJmnQ1

**Comment by jdanyow** [comment]
@mbroadst - I took a look at the plunker you put together [here](https://github.com/aurelia/binding/issues/152#issuecomment-132286888).

The issue you're seeing is the inputs are initially blank but when you click add-new they end up with the word `undefined` in them.

What you've uncovered is an inconsistency in the binding code.  When the view is initially bound to the view-model, the binding code does not assign the view-model value to the view when the value is undefined:

https://github.com/aurelia/binding/blob/master/src/binding-expression.js#L83-L85

Later on, when add-new is pressed, this kind of check does not occur and `undefined` IS assigned to the input element's value property, causing the word `undefined` to appear in the input.

We need to decide on what the expected behavior is here, being mindful that the `targetProperty` isn't always an input per-say but could also be a custom element's bindable prop, etc. 

I will have to defer to @EisenbergEffect on how this should be handled.  Maybe it's as simple as replacing `undefined` and `null` with empty-string when assigning the HTMLInputElement's value property.  This would be consistent with what we do with string interpolation (ie we know the target is a string).  If we go with this approach maybe we should remove the `undefined` check in the `Binding` class... not sure what the implications of that are.

As a work-around, it won't hurt to be explicit and use a value converter, even if it is a bit more verbose:

```javascript
export class CoalesceStringValueConverter {
  toView(value, replacement = '') {
    return value === null || value === undefined ? replacement : value.toString();
  }
}
```
```html
<input value.bind="potentiallyUndefined | coalesceString">
```

**Comment by valichek** [comment]
maybe is related to https://github.com/aurelia/templating/issues/150

**Comment by mbroadst** [comment]
@jdanyow thanks for the detailed writeup!

Wouldn't a more consistent change be to wrap [this](https://github.com/aurelia/binding/blob/master/src/element-observation.js#L88) line in a check for falsiness? I've just checked that locally and it seems to solve the problem for me

**Comment by mbroadst** [comment]
scratch that last idea, if you reset it in the future it doesn't clear it out.. whoops. Preparing a PR with @jdanyow s suggestion to set it to '' now

**Comment by mbroadst** [comment]
https://github.com/aurelia/binding/pull/153/files

**Comment by mbroadst** [comment]
https://github.com/aurelia/binding/pull/153/files
