### ISSUE TITLE
Binding with Maps

### ISSUE THREAD

**Issue by heruan** [aurelia/binding#155]
I'm trying to bind a `class` attribute with a `Map` object, but it seems that setting/removing elements from the map won't trigger change on the `class` attribute.

Here's an example VM:
````javascript
export class Table {
    sort = new Map();

    sortBy(field) {
        if (this.sort.has(field)) {
            if (this.sort.get(field) === 1) {
                this.sort.set(field, -1);
            } else {
                this.sort.delete(field);
            }
        } else {
            this.sort.set(field, 1);
        }        
}
````
and the template:
````html
<table>
    <thead>
        <tr>
            <th click.delegate="sortBy('test')">
                <span>Test</span>
                <span class="${sort.has('test') ? (sort.get('test') > 0 ? 'asc' : 'desc') : 'unsorted'}"></span>
            </th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>
````

My code is more complex, so if the binding should already work I'll post the complete code (any chance to have a jsfiddle-like sandbox to post Aurelia's examples?).

**Comment by heruan** [comment]
Note: using a plain object `sort = {}` instead of a `Map` (and editing the code accordingly) the binding works, so I suppose `Map`s are not supported in such a way. Is it by design or a bug?

**Comment by jdanyow** [comment]
Good questions- this behavior is by-design afaik, let me attempt to explain what's going on:

By switching to a plain object you've replaced the `has` method calls with simple properties.  Properties are observable, which explains why the pojo approach works.  

The binding can't really observe a method invocation like `sort.has('test')` because there's nothing that would notify the binding system that *hey- the "has" method is going to return a different result, you better refresh the binding*.  For this to work, we'd have to dirtycheck expressions like these, which would be overkill for use cases where method-invocation expressions return the same result every time.

**Comment by jdanyow** [comment]
@heruan I forgot to mention- we do have a jsfiddle-like sandbox:

http://bit.ly/aurelia-plunker

**Comment by heruan** [comment]
Thank you @jdanyow! I guessed the observation was on the `Map` object itself, triggering when its underlying properties change and thus refresh the binding. Your explanation is very clear!

**Comment by ChibiBlasphem** [comment]
Hello, I don't know if I can write here. I read a little bit the code of the Map Observer.
And something looked odd to me.
At line 34, we looking for the "add" property of the Map. Shouldn't it be "set". It seems to be copy pasted from "set-observation.js" file
