### ISSUE TITLE
make preventDefault configurable on event bindings

### ISSUE THREAD

**Issue by davismj** [aurelia/binding#16]
Currently, every event is default prevented by default. This breaks the desired behavior of certain events like dragstart. We'd like a way to tell the event handler to allow default behavior. The best way to handle this might be to allow default if the event returns true.

**Comment by stoffeastrom** [comment]
Why not let the consumer handle this completely? E.g don't call preventDefault at all. The native event is already exposed so the consumer may call it.

**Comment by davismj** [comment]
That's fair. Rob?

**Comment by EisenbergEffect** [comment]
That will end up being very tedious since you will now have to return a result from every method. Also, this ends up being unintuitive. Most of the time you want to prevent default. It's easier to just return true when you want to make an exception. Also, solving the problem this way keeps consistency with Knockout and thus makes things more backwards compatible with Durandal.

**Comment by davismj** [comment]
Agreed. I'll keep doing that.

**Comment by stoffeastrom** [comment]
I don't understand what you mean by return a result from every method. I though the event was passed as an argument?

However I do understand what you mean with backward compatibility. As long as it's configurable :)

**Comment by davismj** [comment]
In other words, an event handler should only return a result in a special
case, not the default case.

The event is not passed as an argument. I'd +1 that behavior, though, but
it would have repercussions through the rest of the binding syntax.
