### ISSUE TITLE
Support observing map.get

### ISSUE THREAD

**Issue by davismj** [aurelia/binding#162]
One of the advantages of using a map is using it as a hash table through use of the get method. However, binding to map.get(variable) does not register a subscription.

**Comment by jdanyow** [comment]
related to https://github.com/aurelia/binding/issues/155#issuecomment-135099703

**Comment by heruan** [comment]
Do `Map` and `Set` notify the observer when a value is added/removed? Because binding to `Map`s and `Set`s would be very useful since removing items from arrays is cumbersome. Take this:
```html
<table>
  <tr repeat.for="item of items" click.delegate="$parent.toggleSelected(item)">
    <td><input type="checkbox" checked.bind="$parent.isSelected(item)"></td>
    <td>${item.id}</td>
  </tr>
</table>
```
and
```javascript
export class ItemTable {
  items = [ { id: 1 }, { id: 2 } ];
  selectedItems = new Set();

  isSelected(item) {
    return this.selectedItems.has(item);
  }

  toggleSelected(item) {
    if (this.isSelected(item)) this.selected.remove(item);
    else this.selected.add(item);
  }
}
```
This obviously doesn't work, but if `Set` would tell observers its changes we could tell Aurelia to trigger the update of `isSelected(item)` when `selectedItems` changes.
