### ISSUE TITLE
disable.bind disables button but inner content is still clickable

### ISSUE THREAD

**Issue by ttugrad01** [aurelia/binding#163]
When the disabled.bind condition is met, the button is not clickable but the `<i class="icon-right">`</i> within the button still calls click.delegate when clicked.

``` html
<button disabled.bind="totalCount <= (currentPage * perPage)" click.delegate="nextPage()"><i class="icon-right"></i></button>
```

**Comment by jdanyow** [comment]
Wondering if we need to add special handling for `click` and `disabled` here:
https://github.com/aurelia/binding/blob/master/src/event-manager.js#L6

Quick workaround is to use `click.trigger` instead of `click.delegate` in this case.

**Comment by ttugrad01** [comment]
Thanks for the workaround.  Should the click.delegate one be an open issue?

**Comment by jdanyow** [comment]
Not sure- lets leave this open so @EisenbergEffect has a chance to look at it.

**Comment by sickboy** [comment]
Also ran into this :)

**Comment by mikeobrien** [comment]
:+1:

**Comment by jdanyow** [comment]
We'll add this to the documentation along with some other delegate vs trigger info that I've been tracking [here](http://stackoverflow.com/q/33904248/725866)

**Comment by jdanyow** [comment]
related to #263

**Comment by EisenbergEffect** [comment]
@jdanyow Any thoughts on this?

**Comment by jdanyow** [comment]
only what I had mentioned here: https://github.com/aurelia/binding/issues/163#issuecomment-137216716

**Comment by EisenbergEffect** [comment]
I think we could do this in a point release as well, do you agree?

**Comment by jdanyow** [comment]
yep

**Comment by srfabio** [comment]
Any update on this? I'm having this issue and even using click.trigger won't solve the issue. Looks like the disabled property works well with button elements but not with labels or other inputs

**Comment by sickboy** [comment]
@srfabio labels/other elements don't have a disabled state, only buttons, inputs, etc.
You could check for the condition in the function you execute instead

**Comment by srfabio** [comment]
@sickboy Okay, but since I'm using bootstrap labels and inputs can also have a disabled property which should prevent events. The same code works well (jsfiddle) outside the aurelia application

**Comment by jdposthuma** [comment]
Any ETA on this?

**Comment by MaartenThomassen** [comment]
+1 for this, click.delegate still triggers a disabled button, even with text, latest version of Aurelia.

**Comment by thomas-darling** [comment]
This is a really interesting problem. I'm currently working on handling this and related issues in a component library we're building, and its actually fairly complex. The `disabled` state is an especially  fun one, because not only should it prevent pointer events from reaching the disabled element or children of that element, but it should also affect which element has input focus.

### Preventing pointer events

Preventing pointer events on disabled elements and their children is easy, at least in modern browsers.
All it takes is a single line of CSS:
```css
[disabled] { pointer-events: none; }
```
https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events

Of course, this assumes Aurelia would reflect the value of the `disabled` property to the DOM by adding/removing the `disabled` attribute. Unfortunately this is not the current behavior, but I'm hoping that will be implemented as a result of https://github.com/aurelia/binding/issues/347#issuecomment-242106920.

Until then, I guess a workaround might be to apply a class name:
```html
<button disabled.bind="disabled" class="${disabled ? 'disabled' : ''}">
```
```css
.disabled { pointer-events: none; }
```

### But what about focus?

But this is where it gets fun, because what about the case where an element is disabled programatically while that element, or one of its children, has input focus? Ideally, that element, or its focused child, should then immediately *loose* focus - it would makes no sense to keep focus on a disabled element, as that would allow you to keep typing into e.g. a textbox, even after it, or its parent element, had become disabled.

Diving deeper into this, we realize that a disabled element, and it's children, should also have its `tabindex` attribute set to `-1`, in order to prevent it from receiving keyboard focus if the user presses the `tab` key. And of course, when the element is re-enabled at a later time, all those `tabindex` attributes should be restored to their original values.

### How we currently handle this stuff

I realize this may be getting away from the original topic, but for those curious or in search of inspiration, the approach we're currently taking in the prototype of our component library, is to create *behaviors* which may be *attached* to a custom element - one of those is the `DisabledBehavior` shown below, which handles both the attribute and focus issues described above.

Here we define a *behavior* as a class that can have the same lifecycle methods (i.e `created`, `bind`, `attached`, `detached`, `unbind`) as the view model it is attached to, as well as `propertyChanged` methods for any `@bindable` properties on the view model. We then apply some magic to automatically ensure those methods are invoked on both the view model and any behaviors attached to it - including wiring up observers so any `propertyChanged` methods defined on the behaviors are automatically invoked whenever the value of the corresponding property on the view model changes.
Oh, and we also auto-unsubscribe event listeners when on `detached`.

The `DisabledBehavior`, which relies on `[disabled] { pointer-events: none }` in CSS to prevent the pointer events:
```typescript
export class DisabledBehavior extends Behavior
{
    private _tabIndex: string;

    public constructor(viewModel: any, element: Element)
    {
        super(viewModel, element);
    }

    public attached(): void
    {
        super.attached();

        this.addEventListener("disable", this.disable, false, window);
        this.addEventListener("enable", this.enable, false, window);
        this.addEventListener("enable", this.interceptEnable, false);

        this.disabledChanged();
    }

    public detached(isAutoDetach?: boolean): void
    {
        if (!isAutoDetach)
        {
            throw new Error("This behavior does not support explicit detachment.");
        }

        super.detached();
    }

    public disabledChanged(): void
    {
        let event = this.viewModel.disabled ? "disable" : "enable";
        this.element.dispatchEvent(new CustomEvent(event, { bubbles: true, cancelable: true }));
    }

    private disable(event: Event): void
    {
        let target = event.target as Element;

        if (target === this.element)
        {
            console.log("disabled", this.element);

            this.setBooleanAttribute("disabled", true);

            this.disableKeyboardFocus();
        }
        else if (target.contains(this.element))
        {
            console.log("parent disabled", this.element);

            this.disableKeyboardFocus();
        }
    }

    private enable(event: Event): void
    {
        let target = event.target as Element;

        if (target === this.element)
        {
            this.setBooleanAttribute("disabled", false);

            if (!event.defaultPrevented)
            {
                console.log("enabled", this.element);

                this.enableKeyboardFocus();
            }
            else
            {
                console.log("enabled (parent disabled)", this.element);

                this.disableKeyboardFocus();
            }
        }
        else if (target.contains(this.element))
        {
            console.log("parent enabled", this.element);

            this.enableKeyboardFocus();
        }
    }

    private interceptEnable(event: Event): void
    {
        let target = event.target as Element;

        if (target !== this.element && this.viewModel.disabled)
        {
            event.preventDefault();
        }
    }

    private disableKeyboardFocus(): void
    {
        this.element.blur();

        if (this.element.hasAttribute("tabindex"))
        {
            this._tabIndex = this.element.getAttribute("tabindex");
            this.element.setAttribute("tabindex", "-1");
        }
    }

    private enableKeyboardFocus(): void
    {
        if (this._tabIndex != null)
        {
            this.element.setAttribute("tabindex", this._tabIndex);
            this._tabIndex = null;
        }
    }
}
```

The `Checkbox` custom element using this behavior:
```typescript
import {autoinject, bindable, bindingMode} from "aurelia-framework";
import {Control} from "../../form-controls";
import {DisabledBehavior} from "../../behaviors/disabled-behavior";
import {FocusedBehavior} from "../../behaviors/focused-behavior";
import {PressedBehavior} from "../../behaviors/pressed-behavior";
import {CheckedBehavior} from "../../behaviors/checked-behavior";

@autoinject
export class Checkbox extends Control
{
    public constructor(element: Element)
    {
        super(element);

        this.attachBehavior(DisabledBehavior);
        this.attachBehavior(FocusedBehavior);
        this.attachBehavior(PressedBehavior);
        this.attachBehavior(CheckedBehavior);
    }

    @bindable({ defaultBindingMode: bindingMode.twoWay })
    public disabled = false;

    @bindable({ defaultBindingMode: bindingMode.twoWay })
    public focused = false;

    @bindable({ defaultBindingMode: bindingMode.twoWay })
    public pressed = false;

    @bindable({ defaultBindingMode: bindingMode.twoWay })
    public checked = false;
}
```

I can't say yet whether it is the best solution, but it's working pretty well for us so far - we're just getting started though. I'd actually love to have some kind of framework support for a `behavior` concept like this - maybe a `@behaviors(DisabledBehavior, ...)` decorator on the view model class?
What do you say, @EisenbergEffect? ;-)

Anyways, I just wanted to highlight the challenges related to that innocent looking disabled state, as I think this is about more than just preventing click events, and should probably be handled accordingly :-)

**Comment by ashanvabs** [comment]
today I have add below code to a textarea disabled.bind="isDisableEdit"
expectation was disable textarea when isDisableEdit is true. its work fine in chrome and firefox
but in IE(version 11) it always disable
so I check the html and it was like below
<textarea disabled="" ...
disabled="" attribute makes textarea disable. So any know a way to fix this issue

**Comment by jdposthuma** [comment]
@ashanvabs - this is a separate issue from the one reported here. Anyway...

I don't have this problem on IE 11. Maybe you're using an old version of Aurelia? I'm using aurelia-framework@1.0.7 and aurelia-binding@1.0.9

**Comment by ashanvabs** [comment]
I'm using aurelia-framework@1.0.2 and aurelia-binding@1.0.4.

**Comment by petmat** [comment]
What is the status of this issue? I just ran into this today and was surprised to find this to be such an old issue. Using click.trigger fixed it for me, but I think it would make sense for click.delegate to also work in this context. At the very least it is some weird and confusing behavior.

**Comment by ZoolWay** [comment]
This still seems to be an issue.

To implement a `pointer-events`-CSS-based workaround on my controls I am assigning them a CSS class on the topmost element when they are disabled:

`<template class.bind="elementClass">`

This requires less work than the behaviour solution provided by thomas-darling but might also be less powerful.

**Comment by geomorillo** [comment]
eventually one comes to this place

**Comment by ItWorksOnMyMachine** [comment]
+1 for this issue.

**Comment by Jenselme** [comment]
I think you should use `click.trigger` instead. See https://aurelia.io/docs/binding/delegate-vs-trigger#delegate-vs-trigger

**Comment by jalmansa88** [comment]
Thanks, works fine.

**Comment by Alexander-Taran** [comment]
@EisenbergEffect added to vNext candidates list.
Can be closed
as workaround works fine in vCurrent

**Comment by thomas-darling** [comment]
Just in case it helps anyone else, we're now using the `inert` attribute to disable complex elements. This attribute allows us to mark entire subtrees within the DOM as _inert_, which not only disables pointer events, but also prevents keyboard navigation to elements within those subtrees.

It's not quite a standard yet, but Google provides a polyfill that works really well.
https://github.com/GoogleChrome/inert-polyfill

**Comment by diegopaiva1** [comment]
Is there any concrete solution to this problem?

**Comment by ItWorksOnMyMachine** [comment]
> Is there any concrete solution to this problem?

Use click.trigger instead of click.delegate.

**Comment by diegopaiva1** [comment]
> > Is there any concrete solution to this problem?
> 
> Use click.trigger instead of click.delegate.

Does not work for me.

**Comment by ItWorksOnMyMachine** [comment]
> > > Is there any concrete solution to this problem?
> > 
> > 
> > Use click.trigger instead of click.delegate.
> 
> Does not work for me.

Do you have a repo of this we can look at.  We use it successfully in hundreds of places throughout our app, so there's something else going on here.

**Comment by diegopaiva1** [comment]
> > > > Is there any concrete solution to this problem?
> > > 
> > > 
> > > Use click.trigger instead of click.delegate.
> > 
> > 
> > Does not work for me.
> 
> Do you have a repo of this we can look at. We use it successfully in hundreds of places throughout our app, so there's something else going on here.

Unfortunately I don't, the repository belongs to the company I work for. In any case, if someone is looking for a short, straight answer, the following worked for me:

Wrap the **content** (you may have as many tags as desired) of your `button` around a `div` with a custom class, e.g.:

```html
<button disabled.bind="totalCount <= (currentPage * perPage)" click.delegate="nextPage()">
    <div class="btn-content">
      <i class="icon-right"></i>
    </div>
</button>
```

And then apply the following rule to that class:

```css
.btn-content {
    pointer-events: none;
}
```

**Comment by ItWorksOnMyMachine** [comment]
@diegopaiva1, the example you have still uses click.delegate instead of click.trigger.  change this:
`<button disabled.bind="totalCount <= (currentPage * perPage)" click.delegate="nextPage()">
    <div class="btn-content">
      <i class="icon-right"></i>
    </div>
</button>`

to this:
`<button disabled.bind="totalCount <= (currentPage * perPage)" click.trigger="nextPage()">
    <div class="btn-content">
      <i class="icon-right"></i>
    </div>
</button>`

The difference is where the event handler is attached.  With click.delegate you get a single event handler attached to the document that dispatches any bound event to it's appropriate handler.  This is a useful performance improvement where you might have a foreach with thousands of rows and potentially thousands of attached events.  Event bubbling is a problem for this method however.  With click.trigger, the event handler is bound directly to the element.  In this case, bubbled events never reach the event handler.

**Comment by diegopaiva1** [comment]
> @diegopaiva1, the example you have still uses click.delegate instead of click.trigger. change this: `<button disabled.bind="totalCount <= (currentPage * perPage)" click.delegate="nextPage()"> <div class="btn-content"> <i class="icon-right"></i> </div> </button>`
> 
> to this: `<button disabled.bind="totalCount <= (currentPage * perPage)" click.trigger="nextPage()"> <div class="btn-content"> <i class="icon-right"></i> </div> </button>`
> 
> The difference is where the event handler is attached. With click.delegate you get a single event handler attached to the document that dispatches any bound event to it's appropriate handler. This is a useful performance improvement where you might have a foreach with thousands of rows and potentially thousands of attached events. Event bubbling is a problem for this method however. With click.trigger, the event handler is bound directly to the element. In this case, bubbled events never reach the event handler.

I know that. I copied OP's `button` on my example. But, like I said earlier, `click.trigger` did not solve my problem, as the event continued to be fired even though the button was disabled. Maybe it is a browser issue, IDK. I am using Google Chrome 98.0.4758.102.

**Comment by ItWorksOnMyMachine** [comment]
@diegopaiva1, got it.  Are you also using a div inside your button?  It might be because a button only allows inline elements as children.  You might try changing the div to a span and see if that helps.
