### ISSUE TITLE
Binding 'value' of a select element disables setting a default selected value other then the first one.

### ISSUE THREAD

**Issue by MaartenThomassen** [aurelia/binding#169]
See this issue on the following plunker: http://plnkr.co/edit/9wryC8?p=preview

When having a View with a select element and a repeat.for in the option element, binding the 'selected' property on the options element to set the default value for some condition (eg. the item's id matches a predefined id set in the VM) only works if the 'value' property on the select element is not bound.

As soon as the 'value' property on the select element is bound (see plunker example), the select always initializes on the first element in the list bound to the repeat.for of the options element. Even if in the VM the property to which the 'value' is bound is explicitly set to some other value in the items list.

**Comment by EisenbergEffect** [comment]
@jdanyow Can you look into this?

**Comment by jdanyow** [comment]
@MaartenThomassen here's a working plunker that shows a couple of ways to do this: http://plnkr.co/edit/ZwUMnD?p=preview

You don't want to bind to both the select element's value and to the option element's selected attribute because the two bindings will conflict with each other.

Here's a link to the "official" plunker: http://bit.ly/aurelia-plunker

**Comment by MaartenThomassen** [comment]
Thanks, that worked!

For some reason, .find is not defined for my type (CustomClass[] in typescript), but using the id example worked since i only needed the id anyway.

BTW, the documentation on this is a bit hard to find, would be great to have this kind of stuff documented somewhere in the new doc system you are working on!
