### ISSUE TITLE
Binding Behaviors

### ISSUE THREAD

**Issue by heruan** [aurelia/binding#170]
What's the status of Binding Behaviors as described in http://www.danyow.net/extending-aurelias-binding-language/? Is there an issue/branch to keep track of work, contribute and test?

**Comment by EisenbergEffect** [comment]
We are currently doing some heavy optimization in the binding library (and by we I mean the very talented @jdanyow). It's going well, but we've got some more work to do still. After that is done, we want to tackle two issues: $parent and binding behaviors. @jdanyow has a prototype implementation for binding behaviors, so once we finish our major optimizations, it should be pretty straight forward and quick for us to implement, we believe.

I'm closing this since it's tracked elsewhere.

**Comment by heruan** [comment]
That's awesome! :+1: Tracked elsewhere you mean in a private repository, or somewhere publicly accessible?

**Comment by EisenbergEffect** [comment]
There's an issue for it....I think on the binding repo.

**Comment by heruan** [comment]
Found: https://github.com/aurelia/templating-binding/issues/25
I thought this was the binding repo and looked for it here, my fault! I'll subscribe to that, thank you!
