### ISSUE TITLE
Weird behavior when value converter object parameter contains an array

### ISSUE THREAD

**Issue by mikeobrien** [aurelia/binding#181]
When I pass an array in an object parameter to a value converter a la:

```html
<tr repeat.for="database of databases | objectFilter: { fields: ['key', 'companies'] }">
    <td>${database.key}</td>
    <td class="ellipsis">${database.companies}</td>
    ...
</tr>
```

The value converter runs, the array is passed into it and the data looks fine, the correct number of results are returned and displayed, but the values are empty:

![image](https://cloud.githubusercontent.com/assets/187817/10314953/70c0eb74-6c25-11e5-9fff-dd6367cd9d96.png)

If I remove the array or make it empty, the results are normal:

![image](https://cloud.githubusercontent.com/assets/187817/10315070/f9b06e00-6c25-11e5-9728-d10842990c61.png)

Stripped out everything in the value converter to make sure it wasn't anything with that, still the same result:

```js
export class ObjectFilterValueConverter {
    toView(array: any[], config: any) {
        return array;
    }
}
```

Am I missing something here or does this look like a bug?

**Comment by jdanyow** [comment]
I think this may be a bug that is fixed in the upcoming release- not 100% sure though.  To confirm could you replace the `['key', 'companies']` part of the binding expression with `foo` and then add a property named `foo` to your vm with a value of `['key', 'companies']`?  

The issue/fix I'm thinking of is https://github.com/aurelia/templating-resources/issues/100

**Comment by mikeobrien** [comment]
Yep, that's probably what it is then. Tried what you said and it worked. I'll close this as duplicate. Thx!

**Comment by jdanyow** [comment]
nice! thanks for reporting/checking :dancers:
