### ISSUE TITLE
mutating array used in repeat.for with ValueConverter not intuitive

### ISSUE THREAD

**Issue by jdanyow** [aurelia/binding#183]
```html
<div repeat.for="foo of values | sort"></div>
```

When an item is push/popped in values, the repeat template controller doesn't update.  This is because the repeat is observing the result of the sort converter, not the actual array instance.

Questions around this come up often in the gitter.  Could we add logic to the repeat to check *is the binding expression a ValueConverter? Is the inner expression a collection? Then observe the inner expression with an array/map observer and when it changes recompute, etc*.

Just brainstorming here- there's probably a bunch of ways to come at this.

cc @EisenbergEffect

**Comment by EisenbergEffect** [comment]
One thing I wondered was, after we finish reworking the binding system, could we enable filters to observe their inputs and somehow trigger the binding expression to refresh. Though, now that I think of it, I'm not sure that would solve this problem.

**Comment by jods4** [comment]
Is the root cause of this that the array observation is done inside the `repeat` custom attribute and it doesn't have knowledge of its data source before going through the value converter?

I was about to open a slightly related issue, but I think I'll post here instead.

Aurelia needs to provide a way for custom elements or attributes to bind to collection and do the observation for them. I am building such components and observing the array, unsubscribe when it changes, etc. is a lot of boilerplate that is repeated in every such component. I would love to do: `@binding({ collectionChanged: "onChange" })` or a similar solution.

Of course, this bug makes it worse and is even a stronger argument for lifting bindable arrays into Aurelia proper.

**Comment by EisenbergEffect** [comment]
With respect to that, there are two scenarios. One in which the array's items are changed. The other in which the property referencing the array Is changed to point to a new array. Both affect bindable properties. I'm not sure if we can represent both of these in a single api or not. Recommendations are welcome.

**Comment by jods4** [comment]
I guess that if the array happened to change (`items = []`), the listening code should be called again in the same way it would be called if a new item was added or removed (`items.push(1)`).

I think that when other framework deliver array mutation details, they tend to have diffs (additions, removals) but also a reset notification for cases that would be too expensive to express as element diffs (e.g. the result of a sort operation, clear, reverse, new array is assigned, etc.)
