### ISSUE TITLE
getArrayObserver no longer fire updates when array is pushed to with apply

### ISSUE THREAD

**Issue by lukechilds** [aurelia/binding#237]
I was using `getArrayObserver` to listen for updates to an array and update the DOM accordingly. I do a request and on response append all the items to my array. The items are specifically positioned in the DOM depending on their size so it's really inefficient to push them all individually and animate them separately. I was using apply to get this to work in one update.

For example: `Array.prototype.push.apply(this.posts, response.posts);`

This was working perfectly, triggering one update on `this.posts` no matter how many items are in `response.posts`.

Demo here:
http://plnkr.co/edit/9pw8ReNHu6C1Yf9hYZPx?p=preview

However the exact same code on the latest beta release fails:
http://plnkr.co/edit/zT2tOUrZDmsjwAj0hkAM?p=preview

Removing all the observer stuff and just logging what's going on in the array shows that the new items are still being added when apply is being used, however `repeat.for` doesn't reflect this, it only adds items added normally through `.push()`:
http://plnkr.co/edit/FwUY9gRpnO141Gfm15do?p=preview

Any ideas?

**Comment by jdanyow** [comment]
In previous releases, `Array.prototype.push.apply(this.posts, response.posts);` worked, but only in chrome.  This is because chrome has Object.observe, which enabled it to observe arrays mutated in this manner.  This code would not have worked in IE/Firefox/Safari.

In the current release we've stopped using Object.observe, even in chrome, because O.o is no longer being championed in TC39 and will be removed from chrome soon.

Stick to using the array *instance's* methods for mutating the array (`myarray.push`, `myarray.pop`, `myarray.splice`, etc) and things will work as expected.

**Comment by lukechilds** [comment]
Thanks for the response, and also thanks for pointing me to the spread operator, I didn't know that existed!

There still seems to be an issue though, unless the syntax for `getArrayObserver` has changed, which is far as I can tell it hasn't, the observer still doesn't fire.

Here's an updated version using the spread operator instead of apply:
http://plnkr.co/edit/rMcIaufytptVpR6bBA0N?p=preview

It doesn't matter if you use `.push()` normally or with the spread operator, the first button you click always gives the error:

`Uncaught TypeError: Cannot read property 'queueMicroTask' of undefined`

**Comment by lukechilds** [comment]
It seems to be this line causing the error:
https://github.com/aurelia/binding/blob/6e801927caf9dfa91eed037e037815b30536946c/src/collection-observation.js#L51

**Comment by jdanyow** [comment]
The issue you're seeing is due to the way you're capturing the reference to the observer locator's `getArrayObserver` method.  It causes the javascript `this` issue.

Change this line:
```js
this.arrayObserver = observerLocator.getArrayObserver;
```
To this: 
```js
this.arrayObserver = observerLocator.getArrayObserver.bind(observerLocator);
```
Or this (if you enable "es7.functionBind" in your babel options):
```js
this.arrayObserver = ::observerLocator.getArrayObserver;
```

Here's a working plunker:
http://plnkr.co/edit/nj2P9TkJev21ZnQ3e0em?p=preview

**Comment by lukechilds** [comment]
You absolute monster, that's sorted it, thanks!
