### ISSUE TITLE
updates to underlaying data of repeat.for always force attach/detach in child views

### ISSUE THREAD

**Issue by mbroadst** [aurelia/binding#242]
**NOTE:** This is probably going to be part of multiple issues, as I can't seem to get the same behavior I experienced a few versions ago and am not sure where to begin..

example code: http://plnkr.co/edit/dFfryVtu3lktodNLVT2e

In this code I have a `GraphPage` which contains a few `MyComponent`s each of which have a sub component `MyGraph`. On `GraphPage` I simulate changing of data every 10s to replace the `datum` variable with potentially new data, however not necessarily new. The data is regenerated every time, but the actual contents of the data are a single property `field` which I ensure always starts at 0 and increases.

My expectation is that if `datum` already has `[ { field: 0 }, { field: 1 }]` and its updated with the same values, then no change should occur (the objects are the same), however, as you can see from running the example the data is always changed no matter what the data is updated with. Am I missing something here?

**Comment by mbroadst** [comment]
This is a far smaller example showing the same behavior: http://plnkr.co/edit/aJ0fsiQ00fi22zzLKFuR?p=info

**Comment by stoffeastrom** [comment]
At a quick glance it seems like you are creating new object references since you use `map`and thus it will change. Is it the same behavior if you keep the object references and just update the `field` property?

**Comment by mbroadst** [comment]
@stoffeastrom well the issue is that I'm retrieving this data (in my actual app) from a rest endpoint. With a recent version of aurelia I was able to do this and the framework was able to diff appropriately and just figure out which items actually changed and needed to be updated. I'm sure if I just updated the `field` property of existing objects I wouldn't see the same behavior, but I'm unclear as to what changed and if that's a bug, or if I need to rework this code to accommodate the change.

**Comment by stoffeastrom** [comment]
For me, it feels a bit magic if Aurelia was doing this kind of stuff. You could utilize `JSONPatch` when merging the data from the rest endpoint. This way you will ensure that references that could be kept are kept.

That said, I don't know if there was some kind of feature doing that..

cc @jdanyow @EisenbergEffect

**Comment by mbroadst** [comment]
@stoffeastrom this is, after all, one of aurelia's core functionalities: change detection :smile:

**Comment by stoffeastrom** [comment]
Yes :) indeed

**Comment by stoffeastrom** [comment]
The magic seems to be happening here https://github.com/aurelia/binding/blob/master/src/array-change-records.js

**Comment by jdanyow** [comment]
@mbroadst great question and excellent timing on this particular question.

[`repeat`](https://github.com/aurelia/templating-resources/blob/1.0.0-beta.1.0.1/src/repeat.js#L24) and [`if`](https://github.com/aurelia/templating-resources/blob/1.0.0-beta.1.0.1/src/if.js#L10) are whats known as "template controller" custom attributes.  That means the element they appear on becomes an html template and the attribute controls creating, adding and removing views based on the data bound to the attribute.

In Aurelia, the act of adding or removing a view follows a strict composition lifecycle (created, bind, attached, detached, unbind).

I believe your question could be worded like this:

>When I replace an array item, why does the `repeat` bound to the array remove the item's corresponding view and add a new view for the new array item?  Doing so triggers the composition lifecycle callbacks and is extra work that I don't need or expect to see happening.

This is not a bug, Aurelia's `repeat` attribute has always behaved this way (for the most part, aside from some bugs).  In a repeat, the array items are essentially the "view-models" and the "views" are instances of the template the repeat attribute appears on.  When the view-model instance changes we must detach+unbind the view from it and attach+rebind the view to the new view-model instance.  In many cases when the template is very primitive, this is unnecessary work.  In other cases where there are complex custom elements or attributes in the repeat template the lifecycle must be followed to avoid memory leaks and unexpected behavior due to components being written without consideration for the underlying data being ripped out from under it and replaced with new data.

---

In your case, at least from what I could see in the plunker, you can replace this logic:

```js
    // replace array contents
    this.datum.splice(0, this.datum.length, ...fakeData);
```

With this:

```js
    // overwrite array contents
    let i;
    for (i = 0; i < Math.min(fakeData.length, this.datum.length); i++) {
      Object.assign(this.datum[i], fakeData[i]);
    }
    for (; i < fakeData.length; i++) {
      this.datum.push(fakeData[i]);
    }
    while (i < this.datum.length) {
      this.datum.pop();
    }
```
http://plnkr.co/edit/XlgAL7jn2B77Muoed6iP?p=info

And you'll have the behavior you're looking for.

---

Coincidentally, we're working on an enhancement where the repeat will analyze it's template and make a determination as to whether it can safely skip the composition lifecycle when the bound array instance is replaced or items within the array are replaced.  Follow https://github.com/aurelia/templating-resources/pull/161 for more info on that.

**Comment by mbroadst** [comment]
@jdanyow ah very cool. yeah I had originally written this code before there was strict adherence to the "composition cycle" mentioned above. That replacement code indeed works, but is a bit verbose! I've only skimmed the linked `templating-resources` PR, but would that essentially compile to the same result? Perhaps some more context...

I'm trying to list a bunch of "overview" objects, each item lists some text data but also contains two "graphs" (really a pie chart and a normal plot) which individually maintain timers and update with restful data. As you can see, individual items in my repeat are pretty heavy. The problem I'm facing is not only jitter when the top level items are replaced/updated, but also that I need to track initialization of the graphs (which is non-trivial, and should only happen once) as well as making sure that the graphs stop updating when the page isn't being actively viewed. In this example I basically want to completely skip the lifecycle for these things as the chances of leaking memory because of following the lifecycle is probably greater than the alternative. 

I'll go ahead and bake the above mentioned method into an inherited base class for the graphs, but it would be fantastic if there was some generic way to let aurelia know that I want to handle the heavy lifting.

**Comment by mbroadst** [comment]
@jdanyow any update on this? I've found a number of cases where the above helper doesn't seem to work unfortunately. I've seen you add some changes around this code, any chance aurelia will "just figure it out" automatically any time soon :smile:

**Comment by jdanyow** [comment]
@mbroadst can this be closed? The `repeat` now has logic to detect whether the template needs the lifecycle. There's also the workaround I mentioned for situations when Aurelia thinks the template does require the lifecycle (eg the template contains custom elements or custom attributes whose implementation use the `bind`/`unbind`/`attach`/`detach`) callbacks.

We can't completely remove the standard behavior because it's used in animation scenarios and in components that require/expect the lifecycle to occur.

**Comment by mbroadst** [comment]
@jdanyow yeah this can be, I was just sort of lurking on the issue for updates on automatically handling it. Would it make sense to expose `overwriteArrayContents` as a helper function of aurelia? Also, I'm still seeing #259 even with your `overwriteArrayContents` workaround.

**Comment by jdanyow** [comment]
@mbroadst does your repeat template include any custom elements or attributes that have `bind`/`unbind`/`attached`/`detached` methods?  

If not, the lifecycle should be skipped

If yes, you should be able to opt out of the lifecycle by pushing the custom-element/custom-attribute name into [this array](https://github.com/aurelia/templating-resources/blob/master/src/analyze-view-factory.js#L5).

**Comment by mbroadst** [comment]
@jdanyow cool sounds good, thanks!

**Comment by EisenbergEffect** [comment]
@jdanyow Perhaps we should create a decorator that you can place on an html behavior that adds it to that list?

**Comment by jdanyow** [comment]
that would be great- I'll open a new issue for this work.
