### ISSUE TITLE
Aurelia cannot observe indexed assignment of an array- at least not without Object.observe

### ISSUE THREAD

**Issue by BruceL33t** [aurelia/binding#245]
I was told that 
> Aurelia cannot observe indexed assignment of an array- at least not without Object.observe, which is no longer being championed in TC39. As long as you use methods on the array instance to mutate the array it will work as you expect. In your case, change  this.somearray[index] = something  to  this.somearray.splice(index, 1, something) .

Updating Aurelia to beta1 has been an absolutely nightmare because of this. Is this really the intended behavior - that we cannot mutate the array and have the views reflect this new array? Changing this to splice won't be a viable solution to me - can anyone come up with a workaround, as to how to get it to work as before? And for what reason did they make this change?

**Comment by jdanyow** [comment]
@BruceL33t sorry you're having a difficult time upgrading your project to beta1.  One thing that's important to keep in mind is *your pre-beta code only worked in chrome*.  All other browsers (IE 11, Edge, FireFox, Safari) would not have worked pre-beta1 or post-beta1 because these browsers did not have Object.observe and were using the observation mechanism that is now used across the board now in beta1.

Aurelia observes array mutation by intercepting calls to the array instance's splice, push, pop, etc, methods.  This allows Aurelia to detect changes to an array instance without any expensive dirty-checking which would require keeping a copy of the array and polling for changes periodically, etc.

With this approach there are tradeoffs.  We're getting vastly improved memory usage, cpu usage and change detection speed at the expense of convenience around indexed array assignment.

It would be good to know more about why changing `this.somearray[index] = something` to `this.somearray.splice(index, 1, something)` won't work.  Is it an aesthetics thing or does this change pose a technical barrier in your project?

**Comment by BruceL33t** [comment]
Thanks for your answer @jdanyow .

I didn't know object.observe had been cancelled, but unfortunately yes that's the sad truth. Your alternative approach is clever, as is all you guys are doing with Aurelia.

I guess we need to adopt using splice etc much more from now on. I just hadn't used it much, and I think I faced a few issues doing deep nested array updates, but unfortunately I don't have the code here right now. Could be just me being a newb though. 

I'll make a follow up comment here, if it ever gets a problem again. Thanks! :-)
