### ISSUE TITLE
Cannot read property 'firstChild' of undefined

### ISSUE THREAD

**Issue by digitzfone** [aurelia/binding#255]
This looks to be an issue with binding so placing it here. I apologize if this is incorrect. The issue I am seeing is when using a property inside of a bound function. I am attaching a plunker that will explain.

http://plnkr.co/edit/7s3n1z

Notice that when I reference section.position from the repeat.for, it throws the error. However, if I change to use $index it works fine. While $index works in this example, it may be that we need access to other properties.

This may be  (probably is) something I am doing wrong, but just wanted to let someone know.

**Comment by jdanyow** [comment]
I think the issue is your `position` properties are strings.  When I change them to numbers, it works:  http://plnkr.co/edit/TTMI62?p=preview

That said, deleting using the `position` property will only work the first time you delete something.  After that the position values aren't guaranteed to be correct because item(s) in the array have been removed.  It's better to use `$index`.  You can also remove all instances of `$parent` in your html templates, this is no longer required in the latest version of Aurelia.

Also, make sure you have the latest version of Aurelia installed:

To force jspm to fully update your project, locate [this section](https://github.com/aurelia/skeleton-navigation/blob/1.0.0-beta.1.0.2/package.json#L61-L75) in your package json and use it to craft a `jspm install` statement.  Here's what the skeleton-navigation project's command to update would be based on [this package.json](https://github.com/aurelia/skeleton-navigation/blob/1.0.0-beta.1.0.2/package.json#L61-L75):

```shell
jspm install aurelia-animator-css aurelia-bootstrapper aurelia-fetch-client aurelia-framework aurelia-history-browser aurelia-loader-default aurelia-logging-console aurelia-router aurelia-templating-binding aurelia-templating-resources aurelia-templating-router bootstrap fetch font-awesome text
```

you should also update systemjs:
```shell
jspm dl-loader --latest
```
