### ISSUE TITLE
d3 bound properties

### ISSUE THREAD

**Issue by mbroadst** [aurelia/binding#274]
Hi, here again with my bi-weekly "I don't think I fully understand the binding system" issue :smile: 

I've got a custom element which I bind an object to which draws d3 graphs with a number of keys for an objects.  Every minute a timer makes a call to a rest endpoint, which returns a list of objects and I'm using the `overwriteArrayContents` method @jdanyow provided me in previous issues to.. well.. overwrite the local array of data. This data, in turn, is used in a `repeat.for` of these d3 custom elements.

The problem I'm facing (again) is that of course the binding engine is not triggering updates to the d3 elements because it's not proactively checking for changes on all of the keys of that object. I totally get that this is the expected behavior, however I was wondering if there was a way to let aurelia know which properties I'm interested in observing as part of the custom element's definition?  For instance, if I _used_ those properties in the template for the d3 element this wouldn't be a problem, but since this is d3 it must all be generated in javascript in the view model so that binding behavior doesn't seem to be triggered.

Please let me know if a plunker would just make this easier to discuss

**Comment by EisenbergEffect** [comment]
@jdanyow I'll let you advise on this one. My first though was to  use a signal but maybe what is required here is for @mbroadst to use the BindingEngine directly to observe specific properties and then respond. (This brings up an interesting use case, if it's actually useful, maybe the binding engine should have an `observeObject` helper that takes an instance and a list of properties (or property paths) to observe.)

**Comment by mbroadst** [comment]
@EisenbergEffect I would _love_ an observeObject helper, I am running into this same issue almost constantly. In some cases I want generic observation, and that's just not going to happen, but in most cases I just want to bind a single object to a custom element rather than binding N properties in explicitly.  Especially in this particular case the entire graph needs to be redrawn any time any of these properties are changed, so if I bound each of them in I'd have to set up `Changed` methods for each of them to call the same function rather than having a single `dataChanged`.

I gave `aurelia-computed` a look, but it doesn't seem to solve this particular use case

**Comment by jdanyow** [comment]
@mbroadst a plunker would be great.  I think I understand the issue based on your comments above and some of the past discussions we've had. I'm betting that `overwriteArrayContents` is allowing you to bypass the repeat behavior that you didn't want but this is causing the complications you mentioned above. I think there are some things we can do to get the behavior you're looking for while avoiding observing a ton of properties.

**Comment by jdanyow** [comment]
I guess I need to update the plunker assets first- will post back here when it's ready

**Comment by jdanyow** [comment]
plunker updated: http://bit.ly/aurelia-plunker

**Comment by mbroadst** [comment]
@jdanyow thanks for the update, here is the  plunker: http://plnkr.co/edit/fD3mpA

You'll note that if you don't use the `overwriteArrayContents` this just works, but in my case the graph is only part of the custom element so it causes noticeable flicker.

**Comment by mbroadst** [comment]
@EisenbergEffect in the meantime, could you expand on your suggestion to deal with the BindingEngine directly? How might one do that? Just DI it into the custom element?

**Comment by EisenbergEffect** [comment]
Yes, you could have it injected.You can see some of the observation methods available to you here: http://aurelia.io/docs.html#/aurelia/binding/1.0.0-beta.1.0.3/doc/api/class/BindingEngine

**Comment by mbroadst** [comment]
@EisenbergEffect so I tried this out, is this what you had in mind?

```
@noView()
@inject(Element, BindingEngine)
export class MyGraph {
  @bindable data = { status: { one: null, two: null, three: null } };
  initialized = false;

  constructor(element, engine) {
    this.element = element;
    this.width = this.height = 150;
    this.radius = (this.width + this.height) / 4;
    
    console.log(engine);
    
    this.observers = [
      engine.propertyObserver(this.data.status, 'one'),
      engine.propertyObserver(this.data.status, 'two'),
      engine.propertyObserver(this.data.status, 'three')
    ];
    
    this.observers.forEach(observer => {
      observer.subscribe(this.dataChanged);
    });
  }
```

It doesn't seem to work, although I'm sure I'm missing something

**Comment by EisenbergEffect** [comment]
I don't see `dataChanged` anywhere.

**Comment by mbroadst** [comment]
@EisenbergEffect I just omitted that, in fact I had just tried this initially:

```
    this.observers.forEach(observer => {
      observer.subscribe(data => { console.log('data: ', data); });
    });
```

to no avail

**Comment by mbroadst** [comment]
@EisenbergEffect the alternative plunker for that approach is here: http://plnkr.co/edit/yRmEsX

**Comment by jdanyow** [comment]
@mbroadst I think what you wanted was the ability to replace the view model's `items` array with a new array instance loaded from the server *without causing the repeat to replace the corresponding `my-graph` elements with new instances*.  Here's a plunker that has this behavior:  http://plnkr.co/edit/bLo7l3?p=preview

I removed the `my-graph` element's `attached` method (and moved the logic to the `dataChanged` method. This change allows the repeat use an optimized strategy for reacting to the items-source changing (because nothing in the repeat's template uses any of the composition lifecycle callbacks). I also removed the overwriteArrayContents method.  If you check the console you'll see two MyGraph instances created and then repeatedly updated as the data changes (vs the standard behavior where new instances would be created and added to the dom each time the data changes).

Soon there will be a decorator you can apply to your custom elements/attributes that tells the repeat that the element doesn't need the composition lifecycle when it's underlying data changes: https://github.com/aurelia/templating-resources/issues/164
When this is added you'll be able to have composition lifecycle methods in your custom elements/attributes while still benefiting from the optimized repeat strategy.

Let me know if I got this right or if it wasn't quite what you were looking for.

**Comment by mbroadst** [comment]
@jdanyow yep this takes care of it, lifecycle hits again! Looking forward to the optional lifecycle decorator, thank you.
