### ISSUE TITLE
Composition Slow In Array

### ISSUE THREAD

**Issue by hmarcelodn** [aurelia/binding#304]
Hi guys,

I tried to use the following code in a large array and it is pretty slow:

`<template repeat.for="item of items">
  <compose view="my-view.html"></compose>
</template>
`

The idea is to create a grid component where cells can be dynamically templated like the one below:

`<template>
	<table class="table" id.bind="id">
		<thead>
			<tr>
				<th repeat.for="col of columns" width="${200}">${col.columnName}</th>
			</tr>
		</thead>
		<tbody>
			<tr repeat.for="item of data">				
				<td repeat.for="col of columns">
					<compose view="dataGridTemplates/${col.template}CellTemplate.html"></compose>
				</td>				
			</tr>
		</tbody>
	</table>
</template>`

Am I choosing the best approach? Is there a suggestion? 

See that working: http://screencast.com/t/Na6MKrMnpinx

Thanks in advanced.

**Comment by EisenbergEffect** [comment]
It's important to realize a couple of things:

* Tables are one of the slowest things the browser can render. The layout engine of the browser has to do crazy things to get them right. So, you might want to think about not using tables.
* Dynamic composition does cause views to be loaded asynchronously, so if you have a lot of different templates, it's going to take time to load each one of those. If your application is bundled, this should be faster because it won't need to make an http request.

If you have a large array, this is an ideal case for our upcoming ui-virtualization plugin. This plugin gives you a `virtual-repeat.for` that renders an array but only renders the items that are visible, providing a scroll bar that virtually scrolls through the array.

For the record, I've never seen anything that slow in Aurelia before...so you definitely have some issues there. It was a long time before anything rendered, which makes me thing there are other things going on your solution too.

**Comment by hmarcelodn** [comment]
@EisenbergEffect Thanks for the explanation.

I am going to give a try to that virtualization plugin and see if it can improve the performance. I just wanted to stress the component and see whats the behaviour was.

Here is my solution at GitHub https://github.com/hmarcelodn/Aurelia-DataGrid

**Comment by EisenbergEffect** [comment]
The ui-virtualizaton plugin may not be ready quite yet...but I would use it for your scenario when it is. However, you've got some other issues going on I think.

**Comment by hmarcelodn** [comment]
I believe the reason is I am using more than 3k of rows. The code is pretty easy, it just repeat and use a template for every cell. Probably templating every cell is the problem. I did it in that way to have two-way binding support and keep attached to the model always. May be the solution could be a plugin like virtualization or just support some pagination to avoid the heavy work of templating and binding every single cell.

Thank you @EisenbergEffect

**Comment by stoffeastrom** [comment]
Just my $0.02

As mentioned it's slow when a table has many cells and used in a default way. However you can speed things up, for example using 
```css
table-layout: fixed
```
>Table and column widths are set by the widths of table and col elements or by the width of the first row of cells. Cells in subsequent rows do not affect column widths.
Under the "fixed" layout method, the entire table can be rendered once the first table row has been downloaded and analyzed. This can speed up rendering time over the "automatic" layout method, but subsequent cell content may not fit in the column widths provided. Any cell that has content that overflows uses the overflow property to determine whether to clip the overflow content.

will speed up things dramatically in my experience. All depends on your use case but if you want performance on an iPad you need to have as few DOM Elements as possible which, as mentioned, can be achieved with virtualization.

**Comment by hmarcelodn** [comment]
@stoffeastrom thanks a lot! I am gonna try that.
