### ISSUE TITLE
Possibility to use native HTML tags as Aurelia elements via "as-element" custom attribute

### ISSUE THREAD

**Issue by niieani** [aurelia/binding#305]
The problem originally came about when trying to use components inside tables, but other use-cases might pop up at some point in the future.
An example:

```html
<table>
  <tbody>
      <tr as-element="custom-row" repeat.for="row of items" model.bind="row"></tr>
  </tbody>
</table>
```

Discussion: https://github.com/aurelia/binding/issues/108

@EisenbergEffect offered to implement.

**Comment by EisenbergEffect** [comment]
Added. This was on the wrong repo though.

**Comment by tkallsen** [comment]
Hi, is this issue reported on the correct repo now? (which one, templating?)

**Comment by EisenbergEffect** [comment]
It was and closed. It has been implemented and released.

**Comment by 4nderss** [comment]
I have tried this fix since i have custom elements i want to repeat inside <tbody>, this is because my custom row template is actually 2 tr's. One is the actual row, and the other is a hidden details row which is displayed on click. I tried to repeat this custom element in the "normal" way and that only worked in chrome, IE rendered the rows outside the actual table. 

I'm now trying to use this fix with the as-element="custom-row", however now IE strips all my <tr> and <td> tags and im only left with some <div> tags that are contained inside my <td>. Chrome works fine as before.

Code is as follows:
table.html
`<table>
	<tbody repeat.for="current of currentRows" >
				<tr as-element="row" model.bind="current"></tr>
				<tr as-element="row-details" model.bind="current"></tr>
	</tbody>
         <tbody repeat.for="historic of historicRows" >
				<tr as-element="row" model.bind="historic"></tr>
				<tr as-element="row-details" model.bind="historic"></tr>
	</tbody>
</table>
`
row.html

`<template>
	<tr>                
		<td class="check">
			<div class="wrap">
				<input type="checkbox"></i>
			</div>
		</td>
		<td class="name">
			<div class="wrap">${model.name}</div>
		</td>
	</tr>
</template>`

Row template is containerless.

**Comment by 4nderss** [comment]
I made a plunk to show the problem, in IE the last table is rendered without td/tr and in chrome it works

http://plnkr.co/edit/4hjqxcXmVLv325y3gvkw

**Comment by EisenbergEffect** [comment]
Try not using containerless. You want a container, that's the tr that you defined.

**Comment by 4nderss** [comment]
Tried but with same result :( 

http://plnkr.co/edit/4hjqxcXmVLv325y3gvkw?p=preview

**Comment by MikaelPorttila** [comment]
Any updates on this issue?
I'm having the same problem, as-element doesn't render correctly in IE.
simple demostration of the issue: https://plnkr.co/edit/7rEfCHoDVfhEktvpurt1?p=preview

**Comment by 4nderss** [comment]
Any news on this? Still breaks on IE for me + I can't use <require> in my template with element-as because it breaks. 

How I want it to work

> ViewModel

```
<tbody as-element="row-model" class="section-body" repeat.for="item of items" model.bind="item">
				
</tbody>
```

> rowmodel.html


```
<template>
<require from="somerequirement"></require>

<tr click.delegate="viewDetails = !viewDetails>
<td>${model.property1}</td>
<td>${model.property2}</td>
</tr>
<tr show.bind="viewDetails">
<td>${model.detail1}</td>
<td>${model.detail2}</td>
</tr>
</template>

```


Currently works without require in chrome but not with, does not work at all in IE. Renders without any tr or td element.
