### ISSUE TITLE
Checkbox binding not working as expected

### ISSUE THREAD

**Issue by searus** [aurelia/binding#320]
Hello!

The problem is slightly long winded to explain, so I have created a plunkr to demonstrate: [https://plnkr.co/edit/oklXIg](https://plnkr.co/edit/oklXIg)

Here are the steps to reproduce:

1. Select "Field 1" and check "A". You will see the badge shows 1 items is selected.
2. Now select "Field 2" and check "1". Again, you will see the badge shows 1 items is selected.
3. Now select "Field 1" again.  "A" is no longer checked.
4. But, now check "B" and you will see "A" becomes checked again.

Please let me know if I can provide any other information.

**Comment by z-brooks** [comment]
I could be off but from what I'm seeing... `repeat` reuses elements/views and the `CheckedObserver` is updated with the new array before the models/values are updated on the checkboxes.  The `repeat` then updates the view and models but this doesn't trigger a `checked` update. Changes to the value/model don't trigger checked updates (try manually changing it)... not sure if that matters though.

This is why the rest of the checkboxes update when you change the state of any checkbox (observer update). If you check **4** then switch you'll see it remains checked since **Field 1** only has 3 elements and **4** is dropped and recreated. 

_(just some notes)_

**Comment by hmarcelodn** [comment]
@searus There is something wrong into you approach. You checked values are not observables. You are filling the array every time you check something. You actually needs to have an observable array with values and a checked boolean property. It will be observed and changes will be kept.

**Comment by searus** [comment]
@hmarcelodn my approach is the same as documented in the Aurelia documentation.  An array of the checked items should be maintained in the property specified in the `checked.bind` attribute.  And, it is.  That works correctly.  What doesn't work is the re-rendering of the items.

**Comment by jdanyow** [comment]
Saw the same thing as @z-brooks when stepping through this. Definitely a bug.
https://gist.run/?id=a0421bcde2f08d92e382
