### ISSUE TITLE
dropdown: change.trigger called before data is updated

### ISSUE THREAD

**Issue by flamerohr** [aurelia/binding#338]
I'm using the property `change.trigger` on the select element, and have found that the value obtained for the same field to be one step behind.

https://gist.run/?id=3a692ae620eee64b4e70
When running this gist, the top value is the actual value of the select (using `value.bind`) and the bottom value is the value seen by `change.trigger`.
Select 1 and the top value shows 1, while the bottom value is still blank.
Select 4 and the top value shows 4, while the bottom value shows 1.

**Comment by jdanyow** [comment]
Relevant bindings: `<select change.trigger="changed()" value.bind="selectVal">`
Issue is both the value binding and the trigger binding are subscribing to the element's change event. If the trigger binding gets the event first, `selectVal` will not have been updated.

Using `change.delegate` will fix the issue.  Reversing the order of the bindings will also fix the issue (`<select value.bind="selectVal" change.trigger="changed()">`) in this specific case but I wouldn't consider this to be a reliable fix for all scenarios due to some browsers alphabetizing the order of attribute lists (Firefox).

Not sure if this is a bug or if we need to define whether two-way bindings will be update before or after trigger event bindings are published (if that's even possible to define in all cases).

@EisenbergEffect thoughts?

**Comment by flamerohr** [comment]
That's interesting, I hadn't thought about switching the order of the bindings.

Main reason it's ordered that way is because of a coding practice in place, where attributes are alphabetised for easier code scanning and more predictable.

**Comment by EisenbergEffect** [comment]
Changing the order isn't something that is going to be stable cross-browser.
@jdanyow I'm not sure if it would be really easy to force the ordering of events. If you want to look into it, feel free. I'm thinking that we might want to recommend an alternative approach.

**Comment by jdanyow** [comment]
agree- @flamerohr go with `delegate` instead of `trigger` wherever possible- better performance and the input binding will update prior to the event handler being invoked.
