### ISSUE TITLE
binding to a property getter uses dirty-checking

### ISSUE THREAD

**Issue by frankwallis** [aurelia/binding#37]
In the skeleton-navigation example app some text is bound to an es5 property

```html
<div class="form-group">
    <label>Full Name</label>
    <p class="help-block">${fullName | upper}</p>
</div>
```
```js
export class Welcome{
  constructor(){
    this.heading = 'Welcome to the Aurelia Navigation App!';
    this.firstName = 'John';
    this.lastName = 'Doe';
  }

  get fullName(){
    return `${this.firstName} ${this.lastName}`;
  }
  ...
}
```

When I run the app (in chrome) I can see that the fullName getter is called roughly every 120ms, despite nothing changing. So it appears to be 'falling back' to dirty-checking. Is this the expected behaviour, and is there another way to write this code so that the binding uses one of the more efficient binding mechanisms?

**Comment by EisenbergEffect** [comment]
Yes, this is expected. There is no way to observe a getter either with Object.observe or with auto-generated properties. So, it must fall back to dirty checking.

However, we have a number of improvements that are planned.

* The binding system is pluggable and we have designed a mechanism for plugging in the notion of "dependencies". So, you could tell the binding system that `fullName` depends on `firstName` and `lastName` and then it won't use dirty checking, it will just update it whenever one of the dependencies changes.

* Right now we poll all dirty checked properties every 120ms. This is so that we don't have to force a people to call something like `digest`. There are a few ways we think we can improve upon this. For example, since the bulk of the system is observable (in theory) we could just run the dirty checks after any normal observable changes. This only works if we're observing the dependencies though. But, it might be that we could combine this with some other technique and get rid of the polling altogether.

* We could also monkey-patch the entire DOM and run dirty checking after every event or async operation. This is pretty hacky though and involves mangled a lot of parts of the DOM, so I don't want to do this if we can avoid it.

We plan to start with the first two improvements and then see how that works out practically before investing any time in the third option. We are holding off on some of this until after we make a few fundamental changes in our binding system.

**Comment by jdanyow** [comment]
@frankwallis when the next release of aurelia/binding goes out (v 0.3.5) you'll be able to use [this aurelia plugin](https://github.com/jdanyow/aurelia-computed/blob/master/README.md) to do what's described in @EisenbergEffect 's first bullet point.

This may get incorporated into the aurelia framework.  Keep an eye on this issue for more details:
https://github.com/aurelia/binding/issues/15

**Comment by frankwallis** [comment]
that looks interesting, thanks for your responses.
