### ISSUE TITLE
Binding to custom attribute doesn't work.

### ISSUE THREAD

**Issue by svenvandescheur** [aurelia/binding#380]
I'm using a custom attribute which I'd like to put some configuration in. This configuration is taken from the value of the custom attribute. However, binding to this doesn't seem to work:

```html
<require from="../attributes/Swipe"></require>
<div swipe.bind="swipe_config">
```

results in:

```html
<div swipe.bind="swipe_config" class="au-target" au-target-id="57">
```

instead of:

```html
<div swipe.bind="swipe_config" class="au-target" au-target-id="57" swipe="[MY_FANCY_VALUE]">
```
Where binding to other properties seems to work perfectly.

**Comment by jdanyow** [comment]
When you data-bind an html attribute, the binding system will assign the underlying DOM property.  For example, when you bind an input element's [`value` html attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input), the binding system assigns the input element's [`value` DOM property](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement). It does not call `input.setAttribute('value', newValue)`. If you bind a label element's `for` attribute, the binding system assigns the label element's `htmlFor` property.  For built-in properties of elements, the property assignment typically has the side effect of also updating the corresponding html attribute.  For ad-hoc properties like `swipe`, there's no corresponding html attribute which is why you're not seeing a swipe html attribute when the `swipe.bind` assigns/creates a `swipe` property on the element.  Try adding the following to get the result you need:

```js
swipeChanged(newValue, oldValue) {
  this.element.setAttribute('swipe', newValue);
}
```

**Comment by EisenbergEffect** [comment]
Note: We have an issue we are tracking and thinking of enabling auto reflection to attributes as an opt-in capability in the future.
