### ISSUE TITLE
When aurelia creates new binding context

### ISSUE THREAD

**Issue by Vizer** [aurelia/binding#411]
Hi guys,
Could someone tell me when aurelia creates new binding context, what exactly causes to do this?

**Comment by EisenbergEffect** [comment]
Each view has its own binding context. @jdanyow can provide further details.

**Comment by jdanyow** [comment]
The "scope" in aurelia is made up of two objects: the `bindingContext` (almost always a view-model instance) and the `overrideContext` which can be thought of as an "overlay" of the bindingContext.  Properties on the `overrideContext` "override" corresponding properties on the `bindingContext`.  It's actually rare for there to be a property on the overrideContext that's "hiding" a property on the bindingContext beneath.  Most of the time the overrideContext is storing extra contextual properties such as `$index`, `$first`, `$last`, `$odd`, `$even` in the case of the repeat, `$event` when event bindings are firing, etc.  The other purpose of the `overrideContext` is to enable scope traversal.  The `overrideContext` also has a reference to the parent `overrideContext` and to it's corresponding `bindingContext` which enables the binding system to traverse the scope as-needed when it evaluates a binding expression.

When are `bindingContext`s created?  Not often.  The `repeat` is the only thing that creates them on the fly that I can think of off-hand (because the repeated template has no vm).  The rest of the time the `bindingContext` is the view-model instance you'd expect it to be.  On the other hand, `overrideContexts` are created on an as-needed basis, typically when it's time to compose a view and view-model.

Does this answer the question?

**Comment by atsu85** [comment]
@jdanyow, it would be nice to have this information in docs as well. Not sure where tough.

**Comment by EisenbergEffect** [comment]
Perhaps a "note" in one of the beds binding docs.

**Comment by Vizer** [comment]
Thanks @EisenbergEffect and @jdanyow. Yes, partially it answers the question, but I would like to clarify some points.
As I understood some components or attributes can create `bindingContext`. It depends on component or attribute implementation and there is no some specific rules for this. right?

As I see `bind` method in components has two arguments, first is `bindingContext `and second is `overridingContext`, right?

And regarding router and nested states. Nested routes should create new independent `scope`(including binding and overriding contexts), right?
