### ISSUE TITLE
propertyObserver.subscribe should probably return a Subscription-like object

### ISSUE THREAD

**Issue by qraynaud** [aurelia/binding#421]
I think that though the pattern `.subscribe(callback)` & `.unsubscribe(callback)` is well known and pretty effective, it sometimes lacks ease of use:
* you need to bind your method in some variable or on your instance, then use this bound method to sub/unsub
* you can't use arrow functions in subscribe without an intermediate variable or you would miss a way to unsub

Returning an object with the `dispose` method already configured would be super cool.

I would like to write:
```js
var subscription = observerLocator.getObserver(obj, 'attr').subscribe(val => {
  if (notOkForTheMoment(val)) return;
  // [...] : do stuff
  subscription.dispose();
});
```

Moreover this would inline the spec with the `EventAggregator` which would be more consistent (and consistency is good right?).

You can keep the old syntax for retro compatibility until rc or even later since the two can work together just fine.

**Comment by EisenbergEffect** [comment]
I think we picked this syntax for compatibility with Rx. @jdanyow can you confirm?

**Comment by jdanyow** [comment]
A while back the property observers returned by the `ObserverLocator` had a `subscribe` method that returned a function.  Executing the function would unsubscribe:

```js
let observer = observerLocator.getObserver(obj, 'myProp');
let dispose = observer.subscribe((newValue, oldValue) => console.log(newValue));
dispose(); // unsubscribes...
```

The binding system was refactored and the `ObserverLocator` became the internal, bare-metal, memory optimized, closure minimized service for subscribing to prop changes.  The API changed to this:

```js
class MyClassThatImplementsTheCallableInterface {  // many binding engine internals implement this interface...
  call(context, newValue, oldValue) {
    ... do something ...
  }
}

let myCallable = new MyClassThatImplementsTheCallableInterface();
let myContext = {} // anything- a string, object, whatever...

let observer = observerLocator.getObserver(obj, 'myProp');
observer.subscribe(myContext, myCallable);
observer.unsubscribe(myContext, myCallable);
```
This API allowed the binding system to rid itself of almost all closures which improved the GC and memory utilization characteristics, as well as the overall performance.

Because we could and to avoid being too disruptive to the community, the subscribe and unsubscribe were overloaded, so that they also accept callbacks.  Nothing in aurelia uses these overloads though.

```js
let myCallback = (newValue, oldValue) => ... do something ...;
observer.subscribe(myCallback);
observer.unsubscribe(myCallback);
```

Both of these APIs are less convenient than the original API.  A new, higher level, `BindingEngine` API was introduced for external consumption...

```js
let observer = bindingEngine.propertyObserver(obj, 'myProp');
let subscription = observer.subscribe((newValue, oldValue) => ... do something ...);
subscription.dispose();
```

And that is the story of the property subscription API :revolving_hearts:

**Comment by qraynaud** [comment]
Thanks for the details. I'll go for the higher level API then. But the `subscribe(context, myCallable)` format would have been good for me too.

It's not visible in the docs on http://aurelia.io/docs.html#/aurelia/binding/1.0.0-beta.1.3.5/doc/api/interface/InternalPropertyObserver. Shouldn't it be documented there?
