### ISSUE TITLE
Initial call to observer function when applying observer subscription

### ISSUE THREAD

**Issue by mjhcamp** [aurelia/binding#450]
Consider the following situation:

```
var observer = this.bindingEngine.propertyObserver(
            this, "propertyName");

observer.subscribe(this.propertyObserver);
```

In this situation the function 'propertyObserver' is not called until property 'propertyName' gets a new value. I think it would make more sense if the change handler is called directly when the observer is applied (unless the object is undefined). The change handler has never been fired for the initial state of the object, and the system will have the default state even if the object might have been updated already before the subscription was applied.

Currently I resolve this issue by calling the observer function myself after applying the subscription, I would be nice however to have the observer handle this situation automatically (it could be a property of the subscription).

**Comment by EisenbergEffect** [comment]
We can't change this since it would break thousands of applications built by our community.

I'm not sure this expectation is generally held. Personally, I wouldn't expect any handler to be called because the property hasn't actually changed.

I suggest that if you want this behavior, create a helper method and attached it to the binding engine (or write your own class that wraps the binding engine and provides it). The helper method can do the subscription and invoke the callback as desired.

**Comment by MJLHThomassen** [comment]
Just out of curiosity, how would you go about creating that helper method in Typescript (since you can't change the provided Typescript interface for the BindingEngine).

**Comment by EisenbergEffect** [comment]
I believe those interfaces are open now and can be extended. But if not, you can always just wrap the class in a custom helper class. That's the way it would be done in most other strongly typed languages.

**Comment by MaartenThomassen** [comment]
Ah like that yes, hadn't thought about it that way yet. Thanks!
