### ISSUE TITLE
Use Proxy instead of Object.observe

### ISSUE THREAD

**Issue by Gheoan** [aurelia/binding#459]
**I'm submitting a feature request**

**Current behavior:**
Object observation has some edge cases (I am only aware of the one related to array property access) and can fallback to dirty-checking.

**Expected/desired behavior:**
* **What is the expected behavior?**
In [environments that support `Proxy`](http://caniuse.com/#search=proxy), object observation should work flawless and never fallback to dirty-checking.

* **What is the motivation / use case for changing the behavior?**
Progressive enhancement. Improved performance. 
Developers are confused with object observation's edge cases, but this feature might produce more confusion, because object observation will differ across environments.

**Comment by EisenbergEffect** [comment]
@Gheoan We don't use Object.observe at all. That was removed a long time ago.
Also, I don't know that Proxy will help because it would require a developer to not work with their own object anymore. They would have to instantiate the Proxy and then use that instead. Proxies are likely not very performant right now either. I'm going to close this for now. We are investigating various ways to improve perf and reduce dirty check fallback always.

**Comment by Gheoan** [comment]
I meant "Use Proxy in the same way Object.observe was used before it was removed". 
The developer would not see any `Proxy` in their code. Aurelia would instantiate the Proxy for the developer and replace the original object with the proxy. This proxy would behave exactly like the original object except it may notify subscribers of changes to the objects. I thought Proxy is more performant than dirty-checking, but I have no proof.
