### ISSUE TITLE
Using the same valueconverter on shared property causes an endless loop

### ISSUE THREAD

**Issue by EisenbergEffect** [aurelia/binding#482]
@4nderss commented on [Mon Aug 22 2016](https://github.com/aurelia/templating/issues/452)

**I'm submitting a bug report**

* **Library Version:**
1.0.3

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
5.9.1

* **NPM Version:**
3.10.5

* **JSPM OR Webpack AND Version**
Aurelia CLI

* **Browser:**
Chrome 

* **Language:**
all

**Current behavior:**
I am using a valueconverter (sorter) on a dependency injected container-class. My use case is I have a list displayed with minimal details. When pressing a 'show details' button a dialog appears with the same list but more details. I want to show the list and re-use a custom valueconverter (sorter) to sort both the first list and the second. 

When the list is rendered on the first view and sorted, there are no issues. However when the dialog is attached and the second list is rendered in the dialog, the valueconverter triggers a re-render of the first list. This results in both the lists triggering re-render on eachother and an endless loop hangs the browser. 

Problem can be viewed here ( https://gist.run/?id=20e6fcd1e2b79ea16cf2a31606ade0eb )
Uncomment the second table and run, browser will hang. 

**Expected/desired behavior:**
I expect to be able to re-use a valueconverter on a shared property without getting endless loop

* **What is the expected behavior?**
Rendering of both views without problems.

* **What is the motivation / use case for changing the behavior?**
Being able to re-use shared resources without having problems if they appear in the DOM at the same time.

**Comment by jdanyow** [comment]
`array.sort` mutates the actual array instance (unlike methods like `filter` which create a new array instance).  Make a shallow copy of the array in your converter before invoking the sort method otherwise every time the array is sorted by one instance of your value-converter binding expression it will cause side-effects / unnecessary rendering work for other parts of your template that use the same property.

change this: `array.sort(this.sort)`
to this: `array.slice(0).sort(this.sort)`

**Comment by 4nderss** [comment]
Ah, I thought the solution would be something like that. Was unsure about binding behaviors when returning a shallow copy. 

Thanks for the help
