### ISSUE TITLE
Third-party lib only works on input on Firefox if I remove value.bind

### ISSUE THREAD

**Issue by guivr** [aurelia/binding#536]
- **Library Version:**
"aurelia-binding": "npm:aurelia-binding@^1.0.0",

**Please tell us about your environment:**
- **Operating System:**
  OSX 10.10.4 & Linux Ubuntu
- **Node Version:**
  5.2.0
- **NPM Version:**
  3.3.12
- **JSPM OR Webpack AND Version**
  JSPM 0.16.15
- **Browser:**
  Firefox 49.0.2
- **Language:**
  ESNext

**Current behavior:**
Hi. I'm trying to use a third-party lib called "cleave.js" https://github.com/nosir/cleave.js/
I have the following index.html:
```
<input ref="brRG" type="text" value.bind="RG" class="form-control" placeholder="RG">
```

And my index.js
```
import 'cleave.js';

  export class Welcome {
    attached() {
      var cleaveCPF = new Cleave(this.brRG, {
        delimiters: ['.', '.', '-'],
        blocks: [3, 3, 3, 2],
        uppercase: true,
        numericOnly: true
      });
    }
  }
```

It works perfectly on Chrome. However, it does not works on Firefox! It only works on Firefox if I remove `value.bind`.

I think this is a bug. If not, how can I solve this problem?

**Comment by EisenbergEffect** [comment]
Ping @jdanyow

**Comment by jdanyow** [comment]
I'm guessing Cleave is doing something with `input` or `change` events (or potentially not firing those events when it modifies the input's value programatically. If you want to put together a gist that reproduces the issue we can try to help you out: https://gist.run/?id=7542e061bc940cde506b

I bet you could quickly fix this by changing your input value binding to `value.bind="RG & updateTrigger:'blur'"` which tells the binding to update your model only when the input blurs (instead of on every change/input event.

**Comment by LeoNero** [comment]
@jdanyow Your solution worked! Thanks!

**Comment by jdanyow** [comment]
nice! going to close this, thanks for confirming
