### ISSUE TITLE
Bi-directional ValueConverter calls toView before fromView

### ISSUE THREAD

**Issue by stsje** [aurelia/binding#546]
**I'm submitting a bug report**

* **Library Version:**
1.0.9

* **Browser:**
Chrome

* **Language:**
ESNext

**Current behavior:**
Update an input value and notice how `toView` is getting called before `fromView`. I would expect `fromView` to be called first, since the user is updating the value.

Edit the following text input and notice the console logs
https://gist.run/?id=faf634bf1b4ef6178052122638925129
```
toView
fromView
toView
```
`fromView` should be called first, right?

On blur `toView` is being called again. Why is that when the value hasen't changed?

**Comment by StrahilKazlachev** [comment]
If I'm not mistaken `toView` gets called first because the new value gets compared with the one in the VM.

**Comment by stsje** [comment]
@StrahilKazlachev  Why isn't the `fromView` value compared to the actual VM value?
Anyway, I don't see why `toView` is being called twice.

**Comment by jdanyow** [comment]
The binding expression is evaluated in response to input events to determine whether an actual change occurred, instead of blindly assigning the property (which may not expect to be assigned when newValue/oldValue are the same). This is the first toView call you see after editing the input.

The second toView call happens in response to the model property change that occurs when the model property is assigned due to the edit.

We could probably eliminate some of these calls if there were guarantees around input/change events not firing when no actual change occurred and some strong constraints around what is allowed in property getters and setters (very unlikely to ever happen).
