### ISSUE TITLE
Using the throttle binding-behavior on a property getter (`get someComputedProperty()`) only appears to throttle the getter function calls.

### ISSUE THREAD

**Issue by m-andrew-albright** [aurelia/binding#547]
**I'm submitting a bug report**

* **Library Version:**
1.1.1

**Please tell us about your environment:**
* **Operating System:**
Windows 8.1

* **Node Version:**
6.8.0

* **NPM Version:**
4.0.1

* **JSPM**
JSPM 0.16.39

* **Browser:**
Chrome 54.0.2840.99 m | Firefox 50.0.2

* **Language:**
ESNext

**Current behavior:**
Using the `throttle` binding behavior, my view is properly only updating every `n` milliseconds, as you would expect.  However, when using `get someComputedProperty()` and `throttle`, while the view appears to only update in the specified milliseconds, the getter function is being run rapidly over and over again, as though no throttle binding behavior had been specified.

See gistrun: https://gist.run/?id=da6820af6d16927b42719c4b3f6edeca

**Expected/desired behavior:**

* **What is the expected behavior?**
I would expect the property getter function to only be called every time the `n` milliseconds interval specified elapsed.

* **What is the motivation / use case for changing the behavior?**
Performance

I apologize if I am filing this in the wrong repository.

**Comment by EisenbergEffect** [comment]
Ping @jdanyow

**Comment by jdanyow** [comment]
Good question, on the surface this makes sense, let me see if I can explain why it doesn't work this way:

Aurelia observes computed props (props with a getter or setter function) using dirty-checking. The dirty-checking interval is a system-wide setting, 120ms is the default.

The throttle and debounce binding behaviors to not change the way properties are observed, they change the way the binding responds to the property changes. Instead of responding to the property change immediately, the binding's response will be throttled/debounced.

If there were a one-to-one relationship between bindings and properties there might be a nice optimization here to change a particular property observer's dirty-check interval to match the binding's throttle delay. This kind of optimization wouldn't be applicable to debounce though. The reality is there can be multiple bindings that access a particular property, each with different throttles or lack of throttle binding behaviors. It would not be feasible to track *is this property used in only one binding with a throttle? yes- change it's dirty check interval*.

**Comment by m-andrew-albright** [comment]
Thanks for the insight!
