### ISSUE TITLE
Observation of an Element's "xxxx" is not supported.

### ISSUE THREAD

**Issue by olanod** [aurelia/binding#57]
When I use `xxxx.two-way` I get the `Observation of an Element's "xxxx" is not supported.` error.
Is there any kind of restriction for what properties can we bind to?  I tried this with a polymer custom element so if there is a white list of properties that can be two way bound I suggest looking into the properties in the prototype of the element and allow binding on those.

**Comment by EisenbergEffect** [comment]
@jdanyow We need to look into this. We need to allow two way binding to Web Components. In order to do this the current binding system has something built in for registered ElementConfig that specifies how to map properties to events for two-way scenarios on Web Components. I think our recent updates to the binding system may have broken this. Can you take a look and see how e can resolve this issue?

**Comment by EisenbergEffect** [comment]
I'm not sure if the ElementConfig extension point is the best way to handle this. I'm open to alternatives. Also, once we have binding options implemented a two way binding could manually indicate a "trigger" to be used for the binding. This is an override mostly, so I would like a way for the system to determine how two-way binding should work for web components across bindings as well.

**Comment by jdanyow** [comment]
on it
