### ISSUE TITLE
Binding across app instances

### ISSUE THREAD

**Issue by AlainBaslter** [aurelia/binding#582]
**I'm submitting a bug report**

* **Library Version:**
as per March mega release

**Please tell us about your environment:**
* **Operating System:**
Windows 7

* **Node Version:**
6.3.1

* **NPM Version:**
3.10.3

* **JSPM**
JSPM 0.16.52

* **Browser:**
Chrome 56.0.2924.87

* **Language:**
TypeScript 2.2.1

**Current behavior:**

Start from plain vanilla Aurelia Skeleton Navigation Typescript out of the box.
On the welcome page change first name and or last name.
Open a new instance of the app.
Enter first or last name and observe that values change in the text boxes in BOTH app instances!
How is that possible? 

**Expected/desired behavior:**

Binding should be isolates to an app instance.
Changing first/last should not change across instances!

* **What is the motivation / use case for changing the behavior?**

What if users open multiple sessions?
The data across sessions/app instances should not be mangled.
That's a reasonable expectation.

**Comment by EisenbergEffect** [comment]
This is because of BrowserSync. It's designed to keep multiple browsers in sync so you can test across browsers and devices simultaneously. You can turn this off if you don't want it. Also, notice in the command console when you run the app, there's a port for the BrowserSync settings UI where you can change the behavior.
