### ISSUE TITLE
Support Additional SVG Attributes

### ISSUE THREAD

**Issue by EisenbergEffect** [aurelia/binding#59]
We need to ensure that we support as many attributes available in SVG as possible. Here's some documentation that lists attributes: http://www.w3.org/TR/SVG/attindex.html  We need to add any camel cased attributes to our mapping.

**Comment by jdanyow** [comment]
There's tests for a couple attributes here:  https://github.com/aurelia/binding/blob/master/test/property-observation.spec.js#L266-L267

Need to refine how this works because we're using getAttribute/setAttribute in the observer's getValue/setValue methods.  Consider the `height` attribute...  `observer.setValue(3)` is going to work fine.... `observer.getValue()` is going to return a string, "3".  We could return `element.height`, but that's not quite right either:

![debug](http://i.imgur.com/7kONIaF.png)

**Comment by jdanyow** [comment]
As part of this we need to fix the svg + style/css binding issue @AshleyGrant found.
