### ISSUE TITLE
IE10/IE11 <select> repeat/binding doesn't work

### ISSUE THREAD

**Issue by lyptt** [aurelia/binding#595]
**I'm submitting a bug report**

* **Library Version:**
1.2.1

**Please tell us about your environment:**
* **Operating System:**
OSX 10.12

* **Node Version:**
6.2.0

* **NPM Version:**
3.8.9

* **JSPM OR Webpack AND Version**
webpack 2.2.0

* **Browser:**
IE 10 / IE 11

* **Language:**
ESNext

**Current behavior:**
I have a fairly simple custom element that wraps a `<select>` element. It uses a template-wrapped `repeat.for` to fill the contents of the `<select>` element with `<option>` elements. In evergreen browsers I see all of the options come through, whereas in IE10 no elements are rendered.

The custom element template:
```html
<template>
  <select class="select" multiple="">
    <option></option>
    <template repeat.for="option of options">
      <option value="${option.a}">${option.b}</option>
    </template>
  </select>
</template>
```

The ViewModel for this template has a `@bindable` property which gets populated by another template:

```javascript
import {inject, bindable, BindingEngine} from 'aurelia-framework'

@inject(window.Element, BindingEngine)
export class Dropdown {
  @bindable options = []

  constructor (element, bindingEngine) {
    this.element = element
  }

  attached () {
    console.log(window.jQuery(this.element).find('.select')[0].innerHTML)
  }
}
```

In IE10, the above code does not render any <option> elements.

**Expected/desired behavior:**

For <option> elements to successfully render in IE10 / IE 11.

**Additional information**

I've verified that the RequestAnimationFrame and MutationObserver polyfills are installed and working correctly, so this is not an issue specific to polyfilling.

The @bindable variable is traced through other observables, so if MutationObserver was not working, I would expect the list of items to never get updated - this is not the case. The only issue is that the items array is not being rendered into `<option>` elements.

**Comment by lyptt** [comment]
I should note that this is *only* happening with <select>/<option>. If I change the custom element's template to repeat a bunch of <p> tags it works perfectly. There seems to be something specifically wrong with <select>/<option>.

**Comment by lyptt** [comment]
I've confirmed that this is also an issue in IE 11.

**Comment by stsje** [comment]
Put the repeat on the `<option>` element. Also either use `value.bind` or `model.bind`, depending on your needs http://aurelia.io/hub.html#/doc/article/aurelia/binding/latest/binding-selects/3

`<option repeat.for="option of options" value.bind="option.a">${option.b}</option>`

**Comment by lyptt** [comment]
Hi @stsje, yeah I figured out that repeating without a wrapping template element works. I assume this is the intended way it's supposed to work, I've seen conflicting documentation on it however.

**Comment by stsje** [comment]
@lyptt http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/cheat-sheet/4 `Invalid Table Structure When Dynamically Creating Tables` could be the case for selects as well.
IE could most likely be removing the element before Aurelia can see it.

**Comment by lyptt** [comment]
Yeah it sounds like IE's seeing `<template>` and throwing a fit

**Comment by EisenbergEffect** [comment]
@jdanyow Weren't you looking into some IE template issues recently? Any thoughts on the above?

**Comment by tbnovaes** [comment]
@EisenbergEffect  @jdanyow any plans of releasing the fix for this one?

**Comment by RomkeVdMeulen** [comment]
See aurelia/templating/issues/565.

**Comment by EisenbergEffect** [comment]
I don't know that we can fix it due to the fact that the IE parser itself isn't allowing the template element. My recommendation would be to put the repeat on the option itself. To achieve the "static" option element that you had before the original repeat, create an array  that include a model to represent that option along with your dynamic options.

For vNext, we are considering moving templating compilation into the actual application build phase. If we do that, we'll be able to address this issue, I believe. That's a pretty major change in the framework and it's probably 6-12mo out. So, for now, you probably want to attempt the workaround that basis everything on the data model, rather than a combination of dom and data. This is a good approach to consider in general.

**Comment by RomkeVdMeulen** [comment]
@EisenbergEffect I've heard about the mysterious "vNext" a couple of times, and saw the experimental repo. Is there any kind of announcement or blog post yet that explains what you're trying to do?

**Comment by EisenbergEffect** [comment]
I'm hoping  to put together a blog post in the next few weeks. It's *very* early on and truly is experimental. We're trying to work out enough details of what we have in mind so that we can make an intelligent statement on the blog. In essence, it has a lot to do with pushing more into compile-time and out of runtime, so we can provide faster startup time, smaller builds, better support tree-shaking and generally work better with modern tooling.

**Comment by RomkeVdMeulen** [comment]
@EisenbergEffect Thanks for the clarification. I look forward to the blog post.
