### ISSUE TITLE
Using Lodash with MutatingArrayObserver doesn't trigger a binding update

### ISSUE THREAD

**Issue by gkinsman** [aurelia/binding#597]
**I'm submitting a bug report**

* **Library Version:**
1.2.1

**Please tell us about your environment:**
* **Operating System:**
Windows [10]

* **Node Version:**
7.3.0

* **NPM Version:**
3.10.10

* **Browser:**
all 

* **Language:**
all

**Current behavior:**
Using lodash's `_.pull(items, item)` removes the item from the underlying array, but doesn't trigger a binding update. 

**Expected/desired behavior:**
If I instead do a regular `items.splice(items.indexOf(item),1)` then the item is removed correctly, and the binding is updated. 

* **What is the expected behavior?**
http://plnkr.co/edit/YbA5vtLtsUXLP91GffeJ?p=preview

* **What is the motivation / use case for changing the behavior?**
Lodash is a commonly used library and one would think that mutating operations on an array is a pretty common scenario.

**Comment by EisenbergEffect** [comment]
If it's mutating them by using the index directly, we can't detect that change.

**Comment by gkinsman** [comment]
Ultimately it's just using splice, just like the working code...

https://github.com/lodash/lodash/blob/master/.internal/basePullAll.js

**Comment by gheoan** [comment]
Aurelia modifies the splice method in order to detect changes. However, if lodash is loaded before aurelia it will save a reference to the native splice before aurelia can modify it: https://github.com/lodash/lodash/blob/65b148a3b2c8a86da92f51add871b04afddaba59/.internal/basePullAll.js#L7. So, an workaround would be to load lodash after aurelia. There is a change on lodash's master branch that removes the saved reference.
