### ISSUE TITLE
"Binding options" should support debounce or throttling an event

### ISSUE THREAD

**Issue by PWKad** [aurelia/binding#61]
###
Enhancement - add debounce to binding options.

Say we have an input such as -

```
<input value.bind="searchCriteria" onChange.bind="callServer" />
```

Where we want an event to take place that calls the remote server, but only after a specified amount of time, in this case 1000 milliseconds - 

```
<input value.bind="searchCriteria" change.bind="callServer -debounce=1000" />
```

**Comment by EisenbergEffect** [comment]
Interesting...you want to add it to an event also. Syntax would probably be something like this:

`callServer() & debounce:1000`

To mimic filters.

**Comment by PWKad** [comment]
Typically in the past if I was binding to the value directly and performing an action when the value changes I would run across issues where there were too many subscriptions and things going on.  While it of course would probably be better to do this directly on the value I would think the event might be useful as well.

**Comment by EisenbergEffect** [comment]
I think that once we add it to the binding language, we can also teach the event system to do this. That shouldn't be difficult.

**Comment by jdanyow** [comment]
@PWKad @EisenbergEffect would you expect this to throttle view updates to the model (vs model updates to the view) or both? Or should we have `throttleView` and `throttleModel`?

**Comment by jdanyow** [comment]
Also- what what term is idiomatic:  `throttle` or `debounce`?  I have no preference.  Looks like in jQuery terminology they mean different things:  http://benalman.com/projects/jquery-throttle-debounce-plugin/

**Comment by PWKad** [comment]
From my past debounce was more idiomatic but I would guess it is split between the two.

Underscore uses debounce and Knockout uses throttle.  I think the techniques are a bit different though.

**Comment by jdanyow** [comment]
good call- debounce and throttle are indeed different things, we can support both

**Comment by jods4** [comment]
Throttle and Debounce are different things and both Knockout and jQuery support both.

Moreover the story doesn't end here and each has an additional configuration parameter:
- For throttle it's whether a trailing call should happen or not.
- For debounce it's whether the call happens at the beginning or the end.

Google can explain more than I do, so look here for a good explanation:
http://benalman.com/projects/jquery-throttle-debounce-plugin/

They address different scenarios:
- When building an autocomplete box, you would _debounce_ input until it stops (i.e. send a single event, at the end).
- When handling a mouse move or a scroll, you would probably _throttle_ so that everything stays smooth (i.e. update every 100ms even if the event are faster. You surely want to get the last notification as well).

Regarding the additional config, the 2 examples I gave above are probably the correct defaults (debounce.trailing = true; throttle.atEnd = true).

**Comment by jods4** [comment]
One more thing I noticed when looking at the source code.

Debounce/Throttle automatically handle both `updateSource` and `updateTarget`. This should be configurable. Use case: some behavior on a textbox (think autocomplete or filter). When the user types, I want to debounce the `updateSource`. But if the ViewModel changes the field (e.g. clearing it when user hits ESC) I certainly want this to happen immediately.

Note that the interaction between the two is not trivial as a delayed `updateSource` must not override a non-throttled `updateTarget` (and vice-versa).

**Comment by jdanyow** [comment]
@jods4 agreed- in the [prototype](https://github.com/jdanyow/templating-resources/commit/70f6e223bd52f1af5a55e1bad8718395902b5549#diff-ca472a2ebf7b57af219086f27e814124R35) I used a heuristic:  if the binding was two-way or a ListenerExpression (a trigger/delegate expression) we'd throttle/debounce updates to the view model.  Otherwise the throttling/debouncing would rate limit the updates to the view.
