### ISSUE TITLE
TypeError: this.sourceExpression.connect is not a function

### ISSUE THREAD

**Issue by nenadvicentic** [aurelia/binding#685]
**I'm submitting a bug report**

* **Library Version:**
2.0.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
8.11.1

* **NPM Version:**
5.6.0

* **Browser:**
Chrome 66

* **Language:**
all

**Current behavior:**
When there is an error in binding expression in Aurelia template, like:
`<input value.bind="dto..firstName" />`

Stack trace has no information that would help figure where the error originates from. For example:

> Uncaught TypeError: this.sourceExpression.connect is not a function at ChildInterpolationBinding.connect (MarkerClusterGroup.Refresh.js:110) at enqueueBindingConnect (MarkerClusterGroup.Refresh.js:110) at ChildInterpolationBinding.bind (MarkerClusterGroup.Refresh.js:110) at View.bind (MarkerClusterGroup.Refresh.js:110) at If._show (MarkerClusterGroup.Refresh.js:110) at If._update (MarkerClusterGroup.Refresh.js:110) at If.conditionChanged (MarkerClusterGroup.Refresh.js:110) at BehaviorPropertyObserver.selfSubscriber (MarkerClusterGroup.Refresh.js:110) at BehaviorPropertyObserver.call (MarkerClusterGroup.Refresh.js:110) at BehaviorPropertyObserver.setValue (MarkerClusterGroup.Refresh.js:110) at If.descriptor.set [as condition] (MarkerClusterGroup.Refresh.js:110) at Object.setValue (MarkerClusterGroup.Refresh.js:110) at Binding.updateTarget (MarkerClusterGroup.Refresh.js:110) at Binding.call (MarkerClusterGroup.Refresh.js:110) at BehaviorPropertyObserver.callSubscribers (MarkerClusterGroup.Refresh.js:110) at BehaviorPropertyObserver.call (MarkerClusterGroup.Refresh.js:110)

Example stack trace is for template fetched from server, therefore all source-code line references point to the same, random line of code (`MarkerClusterGroup.Refresh.js:110`) . For bundled template, stack trace is similar, but with source-code line numbers being correct. However, both stack traces do not help developer figure where the error originates from.

**Expected/desired behavior:**

* **What is the expected behavior?**

Show meaningful message to help developer determine what the problem is.  At least: 

> Invalid binding expression: "dto..firstName"

**Comment by Alexander-Taran** [comment]
@fkleuver could it be any failure to parse?

**Comment by fkleuver** [comment]
@Alexander-Taran The only scenario where it's (technically) valid syntax is following numeric literals. `2..toString()` mean "convert 2 to a float, then .toString()" it, but binding has never supported that syntax, and I'm reluctant on implementing it unless someone actually needs it.
So in the next version I'll just make it throw whenever it sees two consecutive periods. Clearer to everyone. Pr coming soon.

**Comment by Alexander-Taran** [comment]
@nenadvicentic he did.. yes (-:

**Comment by fkleuver** [comment]
@nenadvicentic @Alexander-Taran The parser generally already does that.

In simplified terms, after an access expression, the parser loops and expects any of these:
- A dot, which is then consumed and proceeds to the next iteration to parse the member expression
- An identifier token, which will be the member expression
- A terminal token (any of `(` `)` `}` `[` `,` `&` `|`) which marks the end of the dot-separated member expression

Just about all cases are covered by this - the terminal token lets the next token bubble back up in the parser, where it's then checked for being a valid expression start. A dot isn't, so a dot following an expression terminal will cause an error (as will other similar cases)

The only reason the double dot slips through is because that loop above will happily keep consuming dot tokens even if they come consecutively. So it must explicitly keep track of, and check for two of them in a row.

This wouldn't be needed if the parser also scanned for the ellipsis token (`...`) which will inherently cause it to throw if there are ever two dots, but there's no point implementing that in this parser without actually implementing the spread/rest functionality, since it's a slight performance degradation.

**Comment by Alexander-Taran** [comment]
@fkleuver understood. so you are covering the not yet covered case.. great

**Comment by fkleuver** [comment]
@Alexander-Taran What do you mean?

**Comment by fkleuver** [comment]
@Alexander-Taran If you're referring to bigopon's comment, I'm working on a commit to cover those cases.
