### ISSUE TITLE
[suggest] support Array.isArray and Number.isFinite in expression

### ISSUE THREAD

**Issue by huochunpeng** [aurelia/binding#709]
**I'm submitting a feature request**

* **Library Version:**
2.1.4

**Please tell us about your environment:**
* **Operating System:**
all

* **Node Version:**
all

* **NPM Version:**
all

* **JSPM OR Webpack AND Version**
NA

* **Browser:**
all

* **Language:**
all

**Current behavior:**
`Array.isArray` and `Number.isFinite` is not visible because it's not in scope of binding context.

**Expected/desired behavior:**

* **What is the expected behavior?**
The new parser supports `typeof` which is a nice feature. But `typeof` is limited (JS legacy). We do need `Array.isArray` and `Number.isFinite` to easily check the data type.

* **What is the motivation / use case for changing the behavior?**
`Array.isArray` is very helpful in checking array type.

Both have a "dot" inside, it might be tricky to implement. This is natually an accessMember but we certainly don't want to expose all `Array` and `Number` object.

Implement them as `isArray` and `isFinite` is easier, but it might confuse users because the real global `isFinite` behaves differently from `Number.isFinite` (our `isFinite` in expression).

cc @fkleuver

**Comment by fkleuver** [comment]
Hmm. Exposing globals is something I discussed with @EisenbergEffect a couple months ago and there was some reason not to do that. Not sure exactly what that reason was.

**Tricky to implement?**
Not really. I'd do that with an extra object lookup during member expression parsing, and send matches off into a new `AccessGlobal` AST class that exposes just this limited API surface.

**Implement as `isArray` and `isFinite`?**
For reasons you already mentioned: probably bad idea. We're doing a subset of the ECMAScript expression syntax, but for that subset that we're doing, I do want to stay as spec-compliant as possible. 

Two ways to do this come to mind:
- Put the `isArray` method on your root binding context. So in your `App`, you do `this.isArray = Array.isArray.bind(Array)`. Binding will traverse up to the root, so it will be available everywhere.
- Make a valueConverter: `foo | isArray` and `foo | isFinite`
    - or a more generic one: `foo | array:isArray`
      (inside the valueConverter: `toView(value, method) { return Array[method](value) }`
    - or even more generic: `foo | global:Array:isArray`
      (`toView(value, obj, method) { switch(obj) case Array: return Array[method](value) }`, etc

In any case, in vNext there will be ways to extend/modify the binding language more easily and it will be possible to expose globals via those extension points. We might be able to back-port that. But I don't think we'll want to expose globals by default.
