### ISSUE TITLE
array repeat not respecting clearing array by setting length to 0

### ISSUE THREAD

**Issue by avrahamcool** [aurelia/binding#710]
**I'm submitting a bug report**

* **Library Version:**
2.1.4

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
v8.11.1

* **NPM Version:**
6.1.0

* **yarn Version:**
1.7.0

**Current behavior:**
when using `repeat.for` on an array,
clearing the array by setting his length to 0 is not recognized.

**Expected/desired behavior:**
mutation to the length of the array is a valid JS way to clear an array, and should be supported by aurelia.

* **What is the expected behavior?**
the repeater should reflect the changes in the array, when we change his length manually.

* **What is the motivation / use case for changing the behavior?**
when working with a lots of data, clearing the array by setting his length to 0 is more efficient than setting a new empty array.

**Workaround**
currently, clearing a array is done by setting a new empty array to the reference.

**Comment by huochunpeng** [comment]
I can reproduce this easily.
https://gist.run/?id=52bbef7ff6b52a39059c2d13f7206fbf
Even worse, the repeat.for doesn't remove dead items even after another push.

@bigopon another regression in repeat :-(

**Comment by bigopon** [comment]
@avrahamcool Thanks for the issue. @huochunpeng @avrahamcool  This feature has never been supported and Aurelia has never made any attempt to intercept `length` property setter.

@jdanyow put it in backlog here #465

I may give it a go after the static router / or if someone feels like picking this up, please send help.

**Comment by bigopon** [comment]
@avrahamcool You can also use `array.splice(0)` to empty the array, just another work around 😃

**Comment by huochunpeng** [comment]
So what's this designed for?

https://github.com/aurelia/binding/blob/a631a77c8f3f2676f2770c4ed5be3a801a4352cf/src/collection-observation.js#L110

https://github.com/aurelia/binding/blob/a631a77c8f3f2676f2770c4ed5be3a801a4352cf/src/observer-locator.js#L168-L170

**Comment by huochunpeng** [comment]
Nvm I got that the code is doing.
It seems to me, without extending ArrayObserver on length, repeat can support this by adding a propertyObserver on items length, then trigger instanceChanged.

**Comment by avrahamcool** [comment]
also, other binding to the array length are not respected.
e.g: interpolation of the length inside the view is working fine for add etc..., but not showing 0 when I set 0 directlly.

https://gist.run/?id=515a8971ed6d13cee5bf79a401cdec44

this might be a different issue.

**Comment by bigopon** [comment]
That's the same issue. The way `length` observer works is exactly the same with how normal array mutation detection works. It assumes `length` only change on mutation, and it also assumes mutation is only done via `push, pop, shift, unshift, reverse, sort, splice`.

**Comment by fkleuver** [comment]
@avrahamcool @huochunpeng @bigopon 

Just to clarify here:

- This is not a regression since it has never worked
- This is not a bug because it cannot work and isn't documented to work (and was never intended to)

The `length` property descriptor of the `Array` prototype is not configurable, this is [by design of the ES spec](https://tc39.github.io/ecma262/#sec-properties-of-array-instances-length).
Therefore it cannot be intercepted by wrapping the prototype in the same way as normal object properties, and methods on the array prototype.

We may (try to) solve this via proxies in vNext, but this likely won't happen in vCurrent as it would include several breaking changes.

### What the length observer does

The length observer is simply a dirty checker whose only purpose is to allow the `length` property to be observed as either a standalone property (for consumption by target observers, such as text in the view) or as part of a computed property.
It does not (and cannot) trigger mutations on the array itself in the way it's currently designed.

(note: it is *technically* possible to make the dirty checker trigger array mutations but this would require significant architectural changes to the observation as it involves synchronizing `.length`-induced changes with regular splices, while the two are timed very differently.)

### How to trigger non-observable mutations such as `.length` or `[index] =`

Every type of array mutation (including directly setting items at certain indices) can be constructed with `.splice()` and this is the recommended way to clear an array or to replace an item in it.

To clear an array (as @bigopon pointed out): use `.splice(0)`. This is not a hack/workaround - this is the normal, [spec-compliant ](https://tc39.github.io/ecma262/#sec-array.prototype.splice) (see point 6) and intended way of clearing an array.

@EisenbergEffect do you want to keep this open for maybe-implement-proxy-at-some-point or shall we keep that as a maybe for vNext?

**Comment by EisenbergEffect** [comment]
Let's keep this as a maybe for vnext.
