### ISSUE TITLE
Unwanted letters appearing in text input after number format convert.

### ISSUE THREAD

**Issue by alaraasa** [aurelia/binding#716]
**I'm submitting a bug report**

* **Library Version:**
aurelia-framework: "1.3.0"

**Please tell us about your environment:**
* **Operating System:**
Linux Fedora 28

* **Node Version:**
10.11.0

* **NPM Version:**
6.4.1

* **JSPM OR Webpack AND Version**
none

* **Browser:**
Chrome 69.0.3497.100 | Firefox 62.0 

* **Language:**
all

**Current behavior:**
I have a text input. It should only contain numbers and has to be shown to the user as 4-digit blocks. My code successfully does these things and the converter always returns the correct value. When I type a single non-digit key two times, that key shows up in the input once, seemingly ignoring the value converter. This does not happen when trying to type different letters in a row. 

**Expected/desired behavior:**
https://gist.run/?id=802356e6073ec4a7914d68be7cb7a203

* **What is the expected behavior?**
When typing letters into the input, they do appear in the input. The value that is returned by the value converter is always set as the value of the input.

* **What is the motivation / use case for changing the behavior?**
Input for payment card number that looks good for the user.

**Comment by bigopon** [comment]
This is an issue with the lacking of context when evaluating for value inside binding / observer. I'm not sure how this behavior can be fixed without a breaking change, but for vNext, it could be already fixed, or a simple fix since evaluation context can be passed along. My suggestion would be to employ some restriction on acceptable input key code range.
cc @fkleuver @jdanyow @EisenbergEffect

**Comment by fkleuver** [comment]
@bigopon @alaraasa When you press the same key twice in a row and you have the value converter filter out that value, then the second key press is not detected as an update (it doesn't differ from the source value at that point). Since the source (your view model) doesn't change, the target (the input value) isn't updated either. This is behaving as expected and wouldn't/shouldn't be any different in vNext, honestly (though it will be easier to do this in vNext)

You can fix this with a BindingBehavior by intercepting the `updateTarget` and `updateSource` methods on the binding to always correct the values in both directions, instead of only when the source has changed.

This is the fixed version of your gist with a binding behavior: https://gist.run/?id=3138ac92b6a0d3c0376af04db037203c

For reference:

```js
export class CardNumberFormatBindingBehavior {
  bind(binding, source, lookupFunctions) {
    const originalUpdateSource = binding.updateSource;
    binding.originalUpdateSource = originalUpdateSource;
    binding.updateSource = value => {
      const cleanValue = value.replace(/[^\d]/g, '');
      binding.updateTarget(cleanValue);
      console.log(`updateSource, cleanValue=${cleanValue}, value=${value}`);
      binding.originalUpdateSource(cleanValue.replace(/\s/g, ''));
    }
    const originalUpdateTarget = binding.updateTarget;
    binding.originalUpdateTarget = originalUpdateTarget;
    binding.updateTarget = value => {
      let cardNumberBlocks = this.createCardNumberBlocks(value);
      if (cardNumberBlocks) {
        console.log("Returning " + cardNumberBlocks.join(" "))
        binding.originalUpdateTarget(cardNumberBlocks.join(" "));
      } else {
        console.log("Returning nothing.")
        binding.originalUpdateTarget("");
      }
    }
  }
  
  unbind(binding, source) {
    binding.updateSource = binding.originalUpdateSource;
    delete binding.originalUpdateSource;
    
    binding.updateTarget = binding.originalUpdateTarget;
    delete binding.originalUpdateTarget;
  }
  
  createCardNumberBlocks(value) {
    if (!value) return "";
    return value.match(/\d{1,4}/g);
  }
}
```

Please let me know whether this solves your problem

**Comment by bigopon** [comment]
Nice @fkleuver. I missed that :+1:

**Comment by alaraasa** [comment]
@fkleuver This works perfectly. Thank you! :slightly_smiling_face:

**Comment by fkleuver** [comment]
You're welcome!
@EisenbergEffect seems this can be closed :)
