### ISSUE TITLE
The value of a model property that is bound to the 'class' attribute of an 'svg' tag is instead ending up in a 'className' attribute 

### ISSUE THREAD

**Issue by ifyio** [aurelia/binding#80]
Given the following custom element template...

```
<!-- svg.class="search" -->
<template>
  <svg role="img" class="${svg.class}">
    ...
  </svg>
</template>
```

The rendered output is as follows...

```
<svg role="img" class="${svg.class} au-target" className="search">
    ....
</svg>
```

Notice that `${svg.class}` is still present in the `class` attribute of the `svg` tag and the values that should have replaced `${svg.class}` have instead been added to a separate attribute called `className`. The expected behaviour is that the value of `svg.class` should be added to the class attribute of the `svg` tag.

**Comment by jdanyow** [comment]
thanks @ifyio - will look into this

**Comment by jdanyow** [comment]
http://stackoverflow.com/a/29525743/725866

Aurelia [remaps](https://github.com/aurelia/templating-binding/blob/master/src/binding-language.js#L19) the "class" attribute name to the dom api property name: "className".

In SVG elements this doesn't work properly because `className` is not a string, but an instance of `SVGAnimatedString`.

**Comment by jdanyow** [comment]
related to aurelia/binding#33
